UC diagram
ByteHamster/PSE pull request #101
Opened 2016-12-11 16:20 UTC by NikoWil

Die neuen Use Case Diagramme.
Bitte genau durchgucken, ich hatte gerade sehr viel Spass beim rebase.

2016-12-11 18:14 UTC, ByteHamster commented
Super, jetzt weiß ich warum mir das eine Bild so hell vorkam :D

Hast du auch innerhalb der UML Dateien rebased? Vom Text her sieht es gut aus.

2016-12-11 18:23 UTC, NikoWil commented
Die alten Bilder wurden ersetzt. Ich denke es passt. Wobei nur die Bilder ersetzen auch kein Problem sein muesste, so lange der Rest passt.
Der rebase war schrecklich...

2016-12-11 19:54 UTC, ByteHamster requested changes
Die Layers passen nicht. Kreise sind unterhalb der Vierecke. In beiden Diagrammen

2016-12-11 20:09 UTC, NikoWil commented
Ja. Nein. Umlet ist doof.
Wenn du die Dateien in Umlet oeffnest sind die layer falsch herum. Sprich, die Kreise unter den Vierecken.
Wenn du es exportierst dreht Umlet das um.

Sieh dir das geloeschte und neue png zur Ueberwachungskonsole an. Auf dem alten war es in Umlet "richtig". Auf dem neuen in Umlet "falsch" aber exportiert richtig.

2016-12-11 20:40 UTC, ByteHamster commented
Lad dir mal die neue Version auf der Homepage runter. Bei mir ist es auch im exportierten Bild falsch. Die Paketquellen scheinen veraltet zu sein.

http://www.umlet.com/changes.htm

2016-12-11 20:43 UTC, NikoWil commented
Verwenden wir nicht die gleichen Paketquellen (Mint)?
Oder hast du schon die Version von der Seite?

2016-12-11 21:21 UTC, ByteHamster commented
Ich hab die von der Seite, weil ich nicht gemerkt hab, dass es das auch in den Paketquellen gibt ^^

2016-12-12 09:00 UTC, ByteHamster approved these changes

2016-12-12 09:05 UTC, merged