[doc] Add the second scenario and its requirements
ByteHamster/PSE pull request #11
Opened 2016-11-29 20:42 UTC by Dav1dK

Das ist das zweite Szenario und die daraus abgeleiteten Anforderungen. Ich habe mich an die Struktur des Plichtenhefts gehalten, dass Hr. Haas uns geschickt hat.

2016-11-29 21:10 UTC, NikoWil requested changes
Wirkt grundsaetzlich passend.
Frage zu den Frequenzen: wie gut sind 500u/ min noch darstellbar in der GUI? Da wuerde ich eine niedrigere Obergrenze nehmen fuer die Visualisierung.
Aehnlich bei Aktualisierungsintervall: nicht 0ms als Untergrenze die wir nicht liefern koennen. Sondern eher 10-20 (wie lange es eben dauert).

2016-11-29 21:21 UTC, ByteHamster requested changes
Änderungswünsche hab ich inline eingetragen. Hauptsächlich Rechtschreibung

2016-11-30 07:49 UTC, ByteHamster requested changes
Hab nochmal ein paar gefunden

2016-11-30 07:49 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\item[340] Die Überwachungskonsole zeigt Drehzahl des Mischermontors an.
zeigt die Drehzahl. Zumindest sind oben auch immer Artikel

2016-11-30 07:49 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\item[360] Der Benutzer kann die Anzeige der Füllstands- und Temperaturverläufe für jeden Tank Ein- und Ausschalten.
Einschalten ist hier nicht substantiviert, müsste also klein geschrieben sein

2016-11-30 07:49 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\item[440] Im Reiter ``Empfangene Daten'' kann für jeden Tank die Anzeige der Füllstands und Temperaturverläufe mittels Checkboxen ein- und ausgeschaltet werden.
Des Füllstands

2016-11-30 07:49 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Als erstes ändert er in der Fertigungssimulation den Zu- und Abfluss bei zwei der Tanks. Nun sehen die Beiden, wie
Beiden klein

2016-11-30 07:49 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +an. Nach einem Klick aus ``Übernehmen'' sehen die beiden, wie in der Überwachungskonsole neue Anzeigen aufgetaucht sind,
Klick auf, nicht aus

2016-11-30 09:54 UTC, Dav1dK commented
Fixed. Ich hab die commits gesquashed.

2016-11-30 10:00 UTC, ByteHamster approved these changes

2016-11-30 10:49 UTC, NikoWil approved these changes

2016-11-30 10:55 UTC, merged