[doc] Added default settings to the NAs.
ByteHamster/PSE pull request #117
Opened 2016-12-12 23:07 UTC by HansMartinA

Uns fehlen noch definierte Standardeinstellungen. Diese werden im Pflichtenheft nur erwähnt, aber nie klar spezifiziert. Am Ende kommt noch jemand auf die Idee, den Schwellenwert für einen Unterlauf standardmäßig auf 100 % einzustellen.

2016-12-12 23:16 UTC, ByteHamster requested changes

2016-12-12 23:16 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[NF] Standardmäßig liegt die Aktualisierungsfrequenz bei 500 Millisekunden.
Es gab irgendwo einen use case, wo der default was anderes war. Ich schreib morgen vor 9 genau, was es war

2016-12-12 23:16 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[NF] Standardmäßig haben die \glspl{OPC UA Client} die Ports 25565, 25566, 25567 und 25568.
Ich würde Server und Client gleich machen. Mir egal welches von beiden. 

Generell ist es eigentlich so, dass man das Betriebssystem die ausgehenden Ports automatisch vergeben lässt, anstatt sie manuell einzustellen. Müsste man vielleicht morgen noch absprechen. Hab ich nur bei einer Websuche gefunden.

2016-12-13 12:08 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[NF] Standardmäßig liegt die Aktualisierungsfrequenz bei 500 Millisekunden.
Standard sollte 1 Sekunde sein. Laut szenarien. Finde ich tatsächlich auch besser, 500ms sind schon ziemlich schnell und belastend für einen default wert

2016-12-13 12:09 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[NF] Standardmäßig haben die \glspl{OPC UA Client} die Ports 25565, 25566, 25567 und 25568.
Das wäre ja dann geklärt, also die einstellbaren Ports als Kann-Kriterium und default auf leerem Feld == automatisch.

2016-12-13 15:40 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +  \item[NF] Standardmäßig haben die \glspl{OPC UA Client} die Ports 25565, 25566, 25567 und 25568.
Ports für die Clients habe ich aus den NFs herausgenommen, da ohne konkrete Zahlen diese dort keinen Sinn mehr machen. Dafür habe ich die Bedeutung der leeren Felder in den FAs aufgenommen.

2016-12-13 16:01 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA730] Leere Eingaben für die Ports der \glspl{OPC UA Client} bedeuten, dass diese noch nicht festgelegt wurden und automatisch durch das Betriebssystem bezogen werden.
Ich mach hier schnell das "noch" weg und merge es dann :)

2016-12-13 16:07 UTC, ByteHamster approved these changes

2016-12-13 16:08 UTC, merged