[doc] Fixed blue color on B/W prints
ByteHamster/PSE pull request #139
Opened 2016-12-15 18:59 UTC by ByteHamster

2016-12-15 19:00 UTC, ByteHamster commented
2 mal regex. Trailing spaces löschen und Sternchen hinzufügen.

2016-12-16 06:56 UTC, Dav1dK requested changes

2016-12-16 06:56 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +Im Nachfolgenden sind die Nummern optionaler Funktionalitäten, die sich aus den Kann-Kriterien ergeben, \textcolor{blue}{*blau} markiert.
"blau und mit Sternchen" anstatt nur blau?

2016-12-17 11:00 UTC, Dav1dK approved these changes

2016-12-17 11:08 UTC, merged