OPC UA
ByteHamster/PSE pull request #202
Opened 2017-02-06 21:16 UTC by ByteHamster

2017-02-06 21:17 UTC, ByteHamster commented
Bitte erst den Parser reviewen ;)

2017-02-06 21:19 UTC, ByteHamster commented
Vielleicht ist ein einzelner Listener für disconnects besser als das Aufrufen der `onError` der einzelnen Listener. Kommentare?

2017-02-08 20:31 UTC, ByteHamster commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +        if (!connected) {
Null check

2017-02-08 20:31 UTC, ByteHamster commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +        try {
Listener null check.

!connected kann auch hier rein

2017-02-11 12:41 UTC, Dav1dK requested changes
Bitte die ganzen final Attribute entfernen.
Außerdem schau bitte nochmal dass es keine Race Conditions gibt. Du hast ja einen AtomicLong verwendet, aber so wie ich das sehe wird auf den nur Synchron zugegriffen, d.h. er wäre unnötig.
Andererseits bin ich mir nicht sicher ob Milo über irgendwelche Handler nicht asynchron auf Attribute zugreift.

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/BooleanReceivedListener.java
>  public interface BooleanReceivedListener extends edu.kit.pse.osip.core.opcua.client.ReceivedListener {
edu.kit.pse.osip.core.opcua.client. weglassen

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/FloatReceivedListener.java
>  public interface FloatReceivedListener extends edu.kit.pse.osip.core.opcua.client.ReceivedListener {
edu.kit.pse.osip.core.opcua.client. weglassen

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/IntReceivedListener.java
>  public interface IntReceivedListener extends edu.kit.pse.osip.core.opcua.client.ReceivedListener {
edu.kit.pse.osip.core.opcua.client. weglassen

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +import com.google.common.collect.Lists;
Haben wir das als Dependency angegeben?

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                .setApplicationUri("urn:edu:kit:pse:osip:client:" + namespace).setEndpoint(endpoint)
Was heißt urn?

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                e.printStackTrace();
Wollen wir wirklich immer den Stack Trace ausgeben? Das machen wir sonst soweit ich weiß nirgends.
Zum debuggen mag es ganz nützlich sein, aber im fertigen Programm würde ich das nicht drinn haben wollen.

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                e.printStackTrace();
Wie wärs wenn wir hier System.err.println("Unsubscribing OPC UA Listener failed") schreiben?

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +        if (listeners.containsKey(listener)) {
Der Konsistenz wegen würde ich im else Zweig eine Exception werfen. Denn wir werfen ja auch immer eine Exception wenn wir nicht connected sind, obwohl wir da einfach blind returnen könnten (siehe auch den nächsten Kommentar).

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +            // Well, this subscription is not registered on the server.
Das würde ich dann auch durchreichen. Denn wenn ich eine Exception bekomme wenn ich nicht connected bin, dann würde ich erwarten eine Exception zu bekommen, wenn es die Subscription nicht gibt. Ich hätte aber auch nichts dagegen nichts zu tun wenn wir nicht connected sind,

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                Unsigned.uint(2), // queue size
Magic Number die besser als Konstente definiert wäre?

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                            } else {
Kann das mit der Abfrage davor überhaupt passieren?

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UANamespaceWrapper.java
> +        server.getNodeMap().addNode(folderNode);
Hinter dieser Zeile sind ein paar Whitespaces.

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UANamespaceWrapper.java
> +            .setAccessLevel(Unsigned.ubyte(AccessLevel.getMask(AccessLevel.READ_WRITE)))
Warum nicht AccessLevel.READ_ONLY?

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UAServerWrapper.java
> +        CryptoRestrictions.remove();
Es sieht falsch aus, remove aufzurufen aber nichts mit dem Return Wert zu machen. Denn eigentlich sind die Restrictions sowieso entfernt worden, damit kannst du ja nur kontrollieren ob es auch wirklich geklappt hat. Also entweder bei false eine Exception werfen, oder weglassen.

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UAServerWrapper.java
> +                    "KinkyDonut",
Ich schlage vor einen anderen Namen zu wählen.

2017-02-11 12:41 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientException.java
> +public class UAClientException extends Exception {
Wie wäre es wenn wir von IOException erben? Passt semantisch besser finde ich.

2017-02-11 14:19 UTC, ByteHamster commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +import com.google.common.collect.Lists;
Uhm gute Frage... Steht nicht in der pom, aber builded ^^ Meinst du, das ist ein Problem?

2017-02-11 14:19 UTC, ByteHamster commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                .setApplicationUri("urn:edu:kit:pse:osip:client:" + namespace).setEndpoint(endpoint)
Uniform Resource Name. Das haben die auch schon so benutzt im Original

2017-02-11 14:31 UTC, ByteHamster commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                            } else {
Ja. Wenn der übergebene Typ zwar zum Wert vom Server passt, aber kein Listener dafür vorgesehen ist. Momentan unterstützen wir ja nur boolean, int, float. Für die haben wir receivedListener, alles andere würde dann den Fehler bekommen

2017-02-11 14:37 UTC, ByteHamster commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UAServerWrapper.java
> +        CryptoRestrictions.remove();
Ist gelöscht. Das größere Problem an der Stelle ist, dass der Port parameter nicht benutzt wird xD

2017-02-12 10:59 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +                            } else {
Ok

2017-02-12 11:06 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +import com.google.common.collect.Lists;
Ja denke ich schon. Entweder es sollte in der POM stehen oder nicht benutzt werden. Allerdings ist das sowieso unnötig. Ersetze einfach `Lists.newArrayListWithCapacity(size)` mit `new ArrayList<>(size)`. Macht genau das selbe aber ist im Oracle JDK enthalten. (`Lists.newArrayListWithCapacity(size)` macht nichts anderes, siehe https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Lists.html#newArrayListWithCapacity(int)).

2017-02-12 11:07 UTC, Dav1dK commented on src/osip-opcua-client/src/main/java/edu/kit/pse/osip/core/opcua/client/UAClientWrapper.java
> +import com.google.common.collect.Lists;
Ich habs schnell geändert^^

2017-02-12 11:09 UTC, Dav1dK approved these changes

2017-02-12 11:13 UTC, merged