Language
ByteHamster/PSE pull request #218
Opened 2017-02-10 08:07 UTC by marimbMax

2017-02-10 08:41 UTC, ByteHamster requested changes

2017-02-10 08:41 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public java.util.ResourceBundle getLocaleBundle() {
Braucht man nicht

2017-02-10 08:41 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +        return singleton.getLocaleBundle().getString(key);
bundle.getString sollte reichen

2017-02-10 08:41 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public void setLocaleBundle(java.util.ResourceBundle bundle) throws TranslatorNullException {
das bundle zeug sollte hier verarbeitet werden. Ansprechen nur über die locale. Dann ist man von außen nämlich unabhängig von der Speicherart

2017-02-10 08:41 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/TranslatorNullException.java
> +    //private static final long serialVersionUID = -4059815426263854286L; No need for now
Die generierte ist besser

2017-02-10 08:41 UTC, ByteHamster commented on src/osip-core/src/test/resources/Bundle.properties
> +greet=hi
Newline

2017-02-10 08:41 UTC, ByteHamster commented on src/osip-core/src/test/resources/Bundle_ge_GE.properties
> +greet=hallo
Newline

2017-02-10 14:55 UTC, Dav1dK submitted a review, later dismissed

2017-02-10 14:55 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public void setLocale(Locale locale) throws TranslatorNullException {
Warum nicht einfach eine NullPointerException?

2017-02-10 14:55 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/utils/language/TranslatorTest.java
> +
Du kannst auch testen ob die Exception geworfen wird.
Dafür einfach statt @Test folgendes schreiben:

@Test(expected = TranslatorNullException.class.class)

2017-02-10 16:34 UTC, marimbMax commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public void setLocale(Locale locale) throws TranslatorNullException {
Ich dachte das wäre irgendwie mehr aussagen.

2017-02-10 16:35 UTC, marimbMax commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/utils/language/TranslatorTest.java
> +
Ist der Test sinnvoll ?

2017-02-10 16:36 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public void setLocale(Locale locale) throws TranslatorNullException {
Ich finde NullPointerException sagt schon genug aus, schließlich hast du ja noch den String. Ich denke, wenn es eine Exception im JDK gibt, die passt, dann kann man die ruhig verwenden.

2017-02-10 16:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/utils/language/TranslatorTest.java
> +
Also ich teste sowas immer...man weiß ja nie was später mal am Code verändert wird, wo der Test dann doch als Regressionstest hilfreich ist.

2017-02-10 17:33 UTC, marimbMax commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/utils/language/TranslatorTest.java
> +
ok

2017-02-11 08:37 UTC, ByteHamster approved these changes

2017-02-11 11:03 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public void setLocale(Locale locale) throws NullPointerException {
NullPointer braucht man nicht extra auszeichnen. Das ist in Java automatisch

2017-02-11 11:04 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/utils/language/Translator.java
> +    public void setLocale(Locale locale) throws NullPointerException {
Ist im Javadoc noch falsch drin

2017-02-11 11:24 UTC, ByteHamster commented
Bitte die NullPointerException komplett entfernen. Muss weder ins Javadoc noch in "throws"-clause

2017-02-11 11:50 UTC, merged