[core/io/parser] Enabled ignored unit test
ByteHamster/PSE pull request #224
Opened 2017-02-10 19:07 UTC by ByteHamster

(and fixed behaviour it was checking)

2017-02-13 16:16 UTC, Dav1dK requested changes

2017-02-13 16:16 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/BaseParser.java
> +            if (toParse.charAt(currentPosition) == '\n') {
Was passiert wenn es zwei oder mehr `\n` gibt? Wäre eine while Schleife dann nicht besser?

2017-02-13 16:28 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/BaseParser.java
> +            if (toParse.charAt(currentPosition) == '\n') {
Das wird extern aufgerufen. Hier ist nur der ganz basic parser. Irgendwo gibt es

```
while(Character.isWhitespace(peak())) pop();
```

2017-02-13 16:28 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/BaseParser.java
> +            if (toParse.charAt(currentPosition) == '\n') {
Das zählt dann einfach von selbst mit

2017-02-13 21:24 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/BaseParser.java
> +            if (toParse.charAt(currentPosition) == '\n') {
Wofür ist diese Änderung dann nötig?

2017-02-13 22:32 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/BaseParser.java
> +            if (toParse.charAt(currentPosition) == '\n') {
Bessere Fehlermeldungen. Wenn der Parser abbricht, kann er jetzt nicht nur den Character anzeigen, in dem das Problem aufgetreten ist. Er kann die Zeile direkt anzeigen

2017-02-14 10:27 UTC, Dav1dK approved these changes

2017-02-14 10:32 UTC, merged