Monitor: Hauptfenster
ByteHamster/PSE pull request #225
Opened 2017-02-11 00:55 UTC by HansMartinA

Baut auf den Tanks auf und ergänzt die MonitoringView um das Hauptfenster.

2017-02-11 08:34 UTC, ByteHamster submitted a review, later dismissed
Listener nicht löschen bitte

2017-02-12 10:48 UTC, ByteHamster commented
Das schau ich mir an, wenn die Tanks gemerged sind. Sonst ist das so doof zu testen

2017-02-12 22:43 UTC, HansMartinA commented
Muss eh noch ein bisschen hier weiter arbeiten.

2017-02-13 16:28 UTC, HansMartinA commented
Alles aktuell und angepasst.

2017-02-14 15:36 UTC, ByteHamster requested changes
Sieht recht gut aus

2017-02-14 15:36 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MainClass.java
> +        MonitoringController.launch(MonitoringController.class, args);
Hier wäre glaube ich Application.launch() schöner. Dann wird klar, dass wir nicht diese seltsamen Aufrufe erfunden haben ^^

2017-02-14 15:36 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/MonitoringMainWindow.java
> +class MonitoringMainWindow {
Die Ampel hat einen recht großen Abstand nach rechts, während sie links direkt anliegt

2017-02-14 15:36 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/MonitoringMainWindow.java
> +class MonitoringMainWindow {
Das Log Feld skaliert momentan nicht in der Höhe mit. Finde, die Tanks sind doch das eigentlich wichtige. Also sollten nicht nur die Tanks kleiner werden, sondern auch dieses Feld

2017-02-14 15:36 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/Light.java
> +            triggeredAlarms--;
Gefällt mir irgenwie nicht... Hab aber auch keine Idee, wie man es besser machen kann

2017-02-14 15:36 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/MonitoringMainWindow.java
> +    private EnumMap<TankSelector, TankVisualization> tanks;
visualizations? Sonst klingt `tanks.get(tank)` so seltsam

2017-02-14 15:36 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsViewFacade.java
> +    public int getTime() {
Bitte umbenennen in `getUpdateInterval()`. `Date.getTime()` ist was komplett anderes aber die Funktion heißt zu ähnlich

2017-02-14 19:44 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/Light.java
> +            triggeredAlarms--;
Du könntest eine Liste machen, in die einfach alle Alarme wandern, die momentan getriggert sind. Dann eben falls es nicht drin ist rein und beim untrigger wieder raus. Würde dich unabhängiger machen von Fehlern im Observable

2017-02-14 23:55 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/Light.java
> +            triggeredAlarms--;
Wenn ein Tank initialisiert wird mit einen Wert, der schon im Alarmbereich liegt, dann funktioniert das glaub nicht

2017-02-16 19:15 UTC, ByteHamster requested changes
Ich weiß, das gehört hier eigentlich nicht rein. Wär trotzdem cool, wenn du das Thermometer von -5 bis 230 machen könntest. Die Komma-Zahl sieht finde ich seltsam aus.

Je mehr ich teste, desto mehr nervt mich das Maximieren :P

2017-02-16 19:15 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.menu.file.settings=Settings
Die Datei sollte `bundle.properties` heißen, nicht `bundle.properties.txt`

2017-02-16 19:15 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.tank.tempUndercoolAlarm=Undercooling alarm
Würde hier das Wort "alarm" fast weglassen. Es ist glaub klar, dass das ein Alarm ist. Frisst nur Platz, wenn man das Fenster nicht so groß hat.

Wenn du bei Überlauf und Unterlauf "Liquid" schreibst, musst du das bei Temperatur auch. Bezieht sich ja beides aufs Liquid

Sollte `monitoring.tank.temperatureUndercoolAlarm` heißen, nicht `temp`

2017-02-16 19:15 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.mixTank.color=Color
`monitoring.title` fehlt noch

2017-02-16 19:15 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.tank.progress.x=Time in milliseconds
Sekunden wären besser. Sonst hat man ja nach 2 Minuten Programm laufen lassen schon 6-Stellige Zahlen. Ist dann wahrscheinlich schwer lesbar.

2017-02-16 22:07 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.menu.file.settings=Settings
Ja, das ist mir bei der Entwicklung der SimulationView aufgefallen. Das hat die Endung beim Speichern nicht akzeptiert. Habe ich geändert.

2017-02-16 22:07 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.tank.tempUndercoolAlarm=Undercooling alarm
Alarm und Liquid ist jetzt weg.
Das mit temperature ist mir auch aufgefallen.

2017-02-16 22:08 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.tank.progress.x=Time in milliseconds
Der Witz ist: Die Verläufe rechnen die Zeit bereits in Sekunden, nur der Label war hier falsch.

2017-02-16 22:08 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties.txt
> +monitoring.mixTank.color=Color
Tatsächlich habe ich das aufgeschrieben, aber nicht übernommen.

2017-02-16 22:11 UTC, HansMartinA commented
Ich weiß, die Zahlen sehen etwas komisch aus. Sind halt keine genauen Zahlen. Aber in dem Fall ist es eine genaue Umrechnung und ich finde, die sollte deswegen so bleiben.

2017-02-16 22:12 UTC, ByteHamster commented
Die Anzeige ist ja dann wieder genau. Bloß die Darstellungsgrenzen werden gerundet

2017-02-16 22:15 UTC, HansMartinA commented
Trotzdem ist es von -3.75°C auf -5°C eine große Rundung.

2017-02-17 11:15 UTC, ByteHamster approved these changes

2017-02-17 16:21 UTC, merged