Server settings wrapper
ByteHamster/PSE pull request #227
Opened 2017-02-11 18:59 UTC by marimbMax

2017-02-11 19:30 UTC, ByteHamster requested changes

2017-02-11 19:30 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +        properties.setProperty(portString, tankString);
Hier sind irgendwie Port und Name vertauscht (Benennung der Strings)

2017-02-11 19:30 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +        properties.setProperty(portString, tankString);
Im Sinne der Erweiterbarkeit würde ich sowas wie port_YELLOW abspeichern, nicht nur YELLOW. Nicht dass wir irgendwann nochmal was anderes pro Tank abspeichern wollen

2017-02-11 19:30 UTC, ByteHamster commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapperTest.java
> +        wrapper.saveSettings();
Hier dann bitte noch

    wrapper = new ...

und wieder lesen, ob es wirklich drin steht

2017-02-11 19:30 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +    public final int getServerPort(TankSelector tank) {
Was passiert, wenn der Port für den Tank noch nicht gespeichert wurde? Dazu am besten noch Test und Spezifikation im Javadoc

2017-02-11 21:51 UTC, ByteHamster commented
Wie wäre es, wenn du zum Testen eine temporäre Datei irgendwo im System erstellst? Dann musst du danach nicht dran denken, die Werte zurückzusetzen. Einfach am Ende die Datei wieder löschen

2017-02-11 21:52 UTC, ByteHamster commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapperTest.java
> +        wrapper.saveSettings();
Momentan testet es ja nur, ob die Werte intern geschrieben werden. Das tatsächliche Schreiben in die Datei wird zwar ausgeführt, aber du schaust nicht, ob es dann auch drin steht

2017-02-11 22:34 UTC, marimbMax commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapperTest.java
> +        wrapper.saveSettings();
Macht das nicht der neue wrapper der erstellt wird ? Der schaut in der Datei nach.

2017-02-11 22:40 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +     * @return The saved port or null if the tank does not exist
Ein int kann nicht null sein

2017-02-11 22:40 UTC, ByteHamster commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapperTest.java
> +        wrapper.saveSettings();
Jup jetzt passt es. Das hab ich vor deinem Commit geschrieben

2017-02-11 22:42 UTC, ByteHamster commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapperTest.java
> +        wrapper.saveSettings();
Jetzt passt es

2017-02-11 22:43 UTC, ByteHamster commented
@Dav1dK ist es eine gute Idee, in den Test hard-coded die Tank enums zu benutzen? Wären TankSelector.valuesWithoutMix()[0] und [1] besser?

2017-02-12 14:58 UTC, ByteHamster requested changes

2017-02-12 14:58 UTC, ByteHamster commented on src/osip-core/src/test/resources/testServerSettings.properties
> +CYAN = 5000
Sollte das nicht serverPort_CYAN heißen? Und warum schlägt dein Test nicht fehl, obwohl das da nicht drin steht? Ist ein Zeichen dafür, dass sich Testläufe gegenseitig beeinflussen, weil sie auf der gleichen Datei arbeiten. Deshalb hatte ich mich für temporäre Dateien ausgesprochen

2017-02-12 16:00 UTC, marimbMax commented on src/osip-core/src/test/resources/testServerSettings.properties
> +CYAN = 5000
Das ist die falsche Datei. Die werden im Target geändert.

2017-02-12 16:19 UTC, Dav1dK reviewed
Also ich stimme HaPe zu. Wir sollten z.B. TankSelector.valuesWithoutMix()[0] als TankSelector Werte benutzen. Dann schlägt der Test nicht fehl wenn wir mal die Tanks umbenennen. Dann müsstest du die Datei aber am Anfang vom Test generieren.
Ich bin ebenfalls dafür temporäre Dateien zu benutzen, damit hintereinander ausgeführte Tests unabhängig voneinander sein.

Also mein Vorschlag: Erstelle in der `@Begin` Funktion eine temporäre Datei (siehe https://docs.oracle.com/javase/7/docs/api/java/io/File.html#createTempFile(java.lang.String,%20java.lang.String)) und schreibe dann den Inhalt der Testdatei manuell rein. Dann kannst du die Namen der TankSelectors mit TankSelector.valuesWithoutMix()[i] bestimmen.

2017-02-12 16:19 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +            throw new NullPointerException();
Wäre gut wenn du hier eine Beschreibung in die Exception speicherst, also z.B. "Properties File is null" oder so.

2017-02-12 16:19 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +            return -1;
Sollte man hier nicht besser eine Exception werfen?

2017-02-12 16:19 UTC, Dav1dK commented on src/osip-core/src/test/resources/testServerSettings.properties
> +CYAN = 5000
Aber das was momentan in der Datei steht ist ja trotzdem falsch, oder?

2017-02-12 16:42 UTC, marimbMax commented on src/osip-core/src/test/resources/testServerSettings.properties
> +CYAN = 5000
Das verstehe ich jetzt nicht. Was ist falsch ? Die Werte ändern sich bei der Datei nicht und werden auch nicht abgefrage. Die betrachtete Datei hat den selben Namen und liegt im Target Ordner bei den Test Sachen. Dort wird auch immer ein Zeitstempel gesetzt bei den Zugriffen.

2017-02-12 16:52 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +            return -1;
Ich hatte ihm vorhin gesagt, er soll -1 zurückgeben.

```
int port = settings.getServerPort() == -1 ? default : settings.getServerPort();
```
vs
```
int port = default;
try {
    port = settings.getServerPort();
} catch (XXException e) {
    //Ignore
}
```

Man könnte natürlich (wie bei Android) einen zweiten Parameter machen, der automatisch benutzt wird, wenn die Settings nicht verfügbar sind.

2017-02-12 16:53 UTC, ByteHamster commented on src/osip-core/src/test/resources/testServerSettings.properties
> +CYAN = 5000
Kann man die Datei dann nicht auch einfach löschen?

2017-02-12 17:43 UTC, Dav1dK commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ServerSettingsWrapper.java
> +            return -1;
Also ein zweiter Parameter wäre auf jeden Fall schöner/kürzer

2017-02-13 14:45 UTC, closed without merging