Opcua controller
ByteHamster/PSE pull request #229
Opened 2017-02-12 13:04 UTC by ByteHamster

Depends on translator changes

2017-02-14 10:09 UTC, HansMartinA requested changes
Mal grob darüber geschaut. Ansonsten ist mir eigentlich nicht viel aufgefallen.

2017-02-14 10:09 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +        client.connectClient();
Ich habe jetzt nicht mehr genau in den Code geschaut. Aber kann es sein, dass connectClient() hier die falsche Methode ist?

2017-02-14 10:09 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +        server.setFillLevel(300.5f);
Wär's nicht besser, die Zahlen, die hier auftauchen, als Konstanten zu definieren?

2017-02-14 10:09 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/AbstractTankServer.java
>  public abstract class AbstractTankServer extends edu.kit.pse.osip.core.opcua.server.UAServerWrapper {
Das Paket sollte hier noch weg.

2017-02-14 10:09 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/MixTankServer.java
>  public class MixTankServer extends edu.kit.pse.osip.simulation.controller.AbstractTankServer {
Das Paket sollte hier ebenfalls weg.

2017-02-14 10:09 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/TankServer.java
>  public class TankServer extends edu.kit.pse.osip.simulation.controller.AbstractTankServer {
Das Paket sollte auch hier weg.

2017-02-14 10:51 UTC, ByteHamster commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +        client.connectClient();
Ups ^^

2017-02-14 10:53 UTC, ByteHamster commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +        server.setFillLevel(300.5f);
Finde bei Tests lohnt sich das nicht. Die Zahlen werden im Abstand von 3 Zeilen genau einmal geschrieben und einmal gelesen. Konstanten wären meine ich eher sinnvoll, wenn die Benutzung weit verstreut ist und man sonst Inkonsistenzen bekommen könnte

2017-02-15 08:45 UTC, HansMartinA requested changes
Nach gründlichem Review...

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/TankClient.java
>       * @param machine The machine to connnect to
"connect", ein n zu viel.

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UANamespaceWrapper.java
Da kann ich nichts kommentieren: In Zeile 133 (neu) "to" ohne zweites t und in Zeile 135 (neu) "browse" mit r.

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +     * Tests of the color can be read correctly
if?

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +     * Tests of the fill level can be read correctly
if?

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +     * Tests of the temperature can be read correctly
if?

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +        server.setFillLevel(300.5f);
Was ist, wenn ich ein genaueren Wert wie 300.581977182371829 testen möchte? Dann muss ich den an den verschiedenen Stellen ändern und nicht an einer einzigen. Ich finde, da lohnt sich eine Konstante schon. Diese kann auch in Form einer lokalen Variable realisiert sein. Wichtig finde ich, dass es nur an einer Stelle steht. Dies ermöglicht beispielsweise auch das Testen mehrerer verschiedener Werte.

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-opcua-test/src/test/java/edu/kit/pse/osip/core/opcua/TankTest.java
> +public class TankTest {
Diese Klasse testet noch nicht alle Methoden des TankServers bzw. TankClients. Außerdem fehlt ein Test für den MixTankClient bzw. MixTankServer.

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/AbstractTankServer.java
> +        addVariable(UAIdentifiers.ALARM_UNDERCOOL, t.getString("opcua.pipe.flowRate"), Identifiers.Boolean);
ALARM_UNDERCOOL kam bereits. Ich glaube, das ist hier falsch.

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/AbstractTankServer.java
>       * Set the color of the liquid in this tank
In Analogie zu den Alarmen sollte hier und nachfolgend "Sets" stehen oder in Analogie zu dem Kommentar bei den Alarmen "Set".

2017-02-15 08:45 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/MixTankServer.java
>   * Server for the mixtank. Contain the motor, in addition to the variables provided in the parent class.
"Contains"

2017-02-15 13:44 UTC, HansMartinA approved these changes

2017-02-15 13:59 UTC, merged