[opcua] Added support for changing the interval by re-subscribing
ByteHamster/PSE pull request #239
Opened 2017-02-15 18:24 UTC by ByteHamster

Also fixed a minor bug when adding variables without folders and subscription IDs

2017-02-18 12:52 UTC, Dav1dK requested changes
Sieht ansonsten gut aus.

2017-02-18 12:52 UTC, Dav1dK commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UANamespaceWrapper.java
> +        if (path.contains("/")) {
Und was ist wenn wir eine Variable ohne "/" adden wollen? Passiert dann garnichts?

2017-02-18 19:11 UTC, ByteHamster commented on src/osip-opcua-server/src/main/java/edu/kit/pse/osip/core/opcua/server/UANamespaceWrapper.java
> +        if (path.contains("/")) {
Hast recht, das war kaputt. Ist behoben.

2017-02-20 14:36 UTC, Dav1dK approved these changes

2017-02-20 15:31 UTC, merged