[WIP][doc] Glossary
ByteHamster/PSE pull request #24
Opened 2016-11-30 21:37 UTC by ByteHamster

2016-12-01 05:04 UTC, ByteHamster commented
Jitter, Makros

2016-12-01 21:00 UTC, marimbMax requested changes
Zeile 49: simulieren wird hier großgeschrieben, denke ich.

2016-12-02 07:09 UTC, ByteHamster commented
Geändert.

2016-12-03 19:59 UTC, ByteHamster commented
@marimbMax Passt das jetzt so?

2016-12-03 20:54 UTC, marimbMax approved these changes

2016-12-03 22:05 UTC, merged