[monitor-settings] Einstellungen
ByteHamster/PSE pull request #240
Opened 2017-02-16 23:26 UTC by HansMartinA

Das Einstellungsfenster. Achtung: Die Änderungen aus dem Branch monitor-vis sind ebenfalls enthalten.

2017-02-18 19:59 UTC, ByteHamster requested changes
- [ ] Bitte einen Abstand zwischen Slider und Textfeld vom update intervall (da stößt die Beschriftung vom Slider am Textfeld an). Vielleicht sogar den slider in die nächste Zeile und die Textbox aligned zu denen der Ports. Das Fenster sieht an der Stelle ein bisschen "ungleichmäßig" aus
- [ ] Die Tank-Namen bitte übersetzen, nicht nur den enum namen nehmen
- [ ] Default host sollte 127.0.0.1 sein (bzw localhost)
- [ ] Zwischen den Alarm-checkboxen der unterschiedlichen Alarme wäre eine Trenn-Linie gut, damit man das schnell auseinander halten kann
- [ ] Wenn man die Zahl vom update intervall ändert und in ein anderes Textfeld klickt, wird der Slider nicht aktualisiert
- [ ] `monitoring.settings.alarms.liquidUnderflow` scheint nicht richtig übersetzt zu sein
- [ ] Bei den tank enums haben wir überall sonst mit `.name()` gearbeitet

2017-02-18 21:47 UTC, HansMartinA commented
Arbeitskopie für mich:

- [ ] Bitte einen Abstand zwischen Slider und Textfeld vom update intervall (da stößt die Beschriftung vom Slider am Textfeld an). Vielleicht sogar den slider in die nächste Zeile und die Textbox aligned zu denen der Ports. Das Fenster sieht an der Stelle ein bisschen "ungleichmäßig" aus
- [ ] Die Tank-Namen bitte übersetzen, nicht nur den enum namen nehmen
- [ ] Default host sollte 127.0.0.1 sein (bzw localhost)
- [ ] Zwischen den Alarm-checkboxen der unterschiedlichen Alarme wäre eine Trenn-Linie gut, damit man das schnell auseinander halten kann
- [ ] Wenn man die Zahl vom update intervall ändert und in ein anderes Textfeld klickt, wird der Slider nicht aktualisiert
- [ ] monitoring.settings.alarms.liquidUnderflow scheint nicht richtig übersetzt zu sein
- [ ] Bei den tank enums haben wir überall sonst mit .name() gearbeitet

2017-02-20 19:27 UTC, ByteHamster commented
> damit keine Aktualisierung des Sliderwertes über die bidirektionale Bindung
Du benutzt `bind` und nicht `bindBidirectional`. Hilft es was, das zu ändern?

2017-02-20 20:29 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java
> +        timeBox.getValueFactory().valueProperty().bindBidirectional(timeSlider.valueProperty());
Ich benutze bereits `bindBidirectional`. Daran liegt es nicht.

2017-02-20 20:35 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java
> +        timeBox.getValueFactory().valueProperty().bindBidirectional(timeSlider.valueProperty());
Huh komisch... Keine Ahnung, wo ich da vorher hingeschaut hab...

2017-02-21 08:52 UTC, ByteHamster requested changes
Drei kleine Sachen noch, die mir aufgefallen sind

2017-02-21 08:52 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsViewFacade.java
>      public void showSettingsWindow(ClientSettingsWrapper currentSettings) {
NullPointerException, wenn listener gesetzt werden, bevor das window angezeigt wird. Das gibt Probleme im Controller. Bitte die currentSettings im Konstruktor übergeben und dort auch das SettingsMainWindow (dann final?) erstellen

2017-02-21 08:52 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java
> +        timeSlider = new Slider(MonitoringViewConstants.MIN_UPDATE_INTERVAL,
Ist es sinnvoll, dass man hier Kommazahlen einstellen kann? Die Millisekunden speichern wir nur als Ganzzahl, soweit ich weiß. Finde, die Kommazahlen gehören hier nicht hin.

2017-02-21 08:52 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/AlarmSettings.java
> +//            currentBox.setSelected(currentSettings.getTempOverheatAlarm(tank, true));
Die sollten noch aktiviert werden

2017-02-21 10:06 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/AlarmSettings.java
> +//            currentBox.setSelected(currentSettings.getTempOverheatAlarm(tank, true));
Stimmt. Habe ich vergessen.

2017-02-21 10:07 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsViewFacade.java
>      public void showSettingsWindow(ClientSettingsWrapper currentSettings) {
Geändert.

2017-02-21 10:08 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java
> +        timeSlider = new Slider(MonitoringViewConstants.MIN_UPDATE_INTERVAL,
> DoubleProperty 	value
The current value represented by this Slider.

Quelle: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Slider.html

Der Slider rechnet mit doubles, d. h. es gibt keine andere Möglichkeit.

2017-02-21 10:09 UTC, HansMartinA commented
Ich habe im Übrigen eine Lösung dafür gefunden, dass beim Herausklicken aus dem Spinner ohne Enter die Änderung nicht übernommen wird. Sie wird jetzt übernommen.

2017-02-21 10:21 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java
> +        timeSlider = new Slider(MonitoringViewConstants.MIN_UPDATE_INTERVAL,
Könntest du es dann so machen?

http://stackoverflow.com/a/38682583/4193263

2017-02-21 10:35 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java
> +        timeSlider = new Slider(MonitoringViewConstants.MIN_UPDATE_INTERVAL,
Gut, danach habe ich nicht gesucht. Habe ich nun hinzugefügt.

2017-02-21 10:51 UTC, ByteHamster approved these changes

2017-02-21 11:03 UTC, merged