Simulation view repair2
ByteHamster/PSE pull request #252
Opened 2017-02-20 19:22 UTC by NikoWil

Diesmal ohne boese Commits von anderen Branches.

2017-02-20 19:40 UTC, ByteHamster requested changes
Ein paar Sachen, die mir beim ersten drüber schauen aufgefallen sind

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +    }
Das sollte wieder weg

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view-interface/src/main/java/edu/kit/pse/osip/simulation/controller/MenuAboutButtonHandler.java
> -public class MenuAboutButtonHandler {
MenuAboutButtonHandler.java im Controller bitte löschen

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view-interface/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationViewInterface.java
>   * Provides abstraction from the view
Author, version (überall)

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/AbstractTankDrawer.java
> +        //TODO: Figure out dynamic font size
TODO

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/MotorDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Dann lieber den Kommentar wegmachen und hoffen, dass es keinem auffällt. Das stimmt nämlich nicht ;)

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/MotorDrawer.java
> +}
Newline

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
Static?

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
Oder halt direkt die Werte vom Objekt nehmen

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +        //TODO: figure out a constant for this
TODO

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +    private void makeLayOut(Stage primaryStage) {
Layout schreibt man normal ohne großes o

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +                timer.schedule(task, delayTime);
Das sieht seltsam aus. Warum?

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Diese Zeile kommt mir bekannt vor. Sollte das nicht nur an einer Stelle sein?

2017-02-20 19:40 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double FILLSENSOR_WIDTH = 0.1;
Hat es einen Grund, dass public und protected gemischt sind?

2017-02-20 20:27 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +                timer.schedule(task, delayTime);
Es wird delayTime (50) ms gewartet, bis der resize stattfindet. Sonst spielt es komplett verrueckt, wenn es immer sofort updaten will.
Kommt in der Zeitspanne eine weitere Aenderung wird wieder neu mit warten angefangen.

2017-02-20 20:28 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Das haben beide Komponenten, die sich drehen. Hast du eine Idee, wie man es vereinheitlichen kann?

2017-02-20 20:28 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double FILLSENSOR_WIDTH = 0.1;
Ein Versehen.

2017-02-20 20:31 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/MotorDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
gemacht.

2017-02-20 20:31 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Ist nicht genau dafür der rotating Drawer gewesen? Dann bekommt der halt paar protected Attribute und man muss am Anfang super.draw() aufrufen. Oder halt wieder ein template

2017-02-20 20:32 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/AbstractTankDrawer.java
> +        //TODO: Figure out dynamic font size
Wuerde ich erst nochmal sehen, wie es dann mit dem engueltigen Text von der Groesse passt.

2017-02-20 20:33 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
static ja.

Direkt vom Objekt nehmen?

2017-02-20 20:33 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/MotorDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Was du aber erklären könntest ist, wo diese riesige Zahl herkommt

2017-02-20 20:34 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
Hmm joa war nur so ne Idee, aber du brauchst die Methode ja an diversen Stellen

2017-02-20 20:36 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +    private void makeLayOut(Stage primaryStage) {
korrekt.

2017-02-20 20:37 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
Aber nur innerhalb von Subklassen.

Aber was genau meinst du mit Werte vom Objekt nehmen? Es werden ja einige Punkte rotiert. Ich schreib sie aber wohl noch um, um direkt einen Point2D zu rotieren...

2017-02-20 20:42 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
An fuer sich ja, wegen einer einzelnen Zeile will ich aber keinen so grossen Overhead aufmachen. Das macht es imho eher unuebersichtlicher

2017-02-20 20:45 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Okay. Dachte, da kann man dann noch mehr auslagern

2017-02-20 20:46 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/AbstractTankDrawer.java
> +        //TODO: Figure out dynamic font size
Dann den bitte einbauen ;)

2017-02-20 20:47 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
Okay. Ne dann passt alles, mach sie einfach static (und Punkt)

2017-02-20 20:48 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +                timer.schedule(task, delayTime);
Na gut

2017-02-20 20:49 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/RotatingControlDrawer.java
> +    public double rotateX(double xPos, double centerX, double yPos, double centerY, double degrees) {
Zu spaet. Ich habe eine Idee... Bleibe gespannt!

2017-02-20 20:49 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/MotorDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Mach ich. Dann diesmal richtig.

2017-02-20 20:51 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/MotorDrawer.java
> +        double elapsedMins = ((double) time) / (1000000000.0 * 60);
Wobei... ne, dann wirds nur noch haesslicher.

2017-02-20 21:10 UTC, NikoWil commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +    }
Ist weg

2017-02-20 21:11 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +                timer.schedule(task, delayTime);
Ansonsten loest jedes Pixel um das die Groesse veraendert wird das neu zeichnen sofort aus.

Wenn man da einmal schnell groesser/ kleiner zieht... viel Spass.

2017-02-21 09:11 UTC, ByteHamster requested changes

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
Das sollte eine menu bar sein, nicht buttons

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +        primaryStage.setHeight(screenDimensions.getHeight());
bitte `setMaximized(true)` stattdessen

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/FillSensorDrawer.java
> +        double compHeight = totalHeight / rows;
Ich finde, die sollten (ähnlich wie die Durchfluss-messer) ihr Seitenverhältnis beibehalten

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/TemperatureSensorDrawer.java
> +        context.fillRect(tempTopLeftX, tempTopLeftY, tempWidth, tempHeight);
Bitte noch ein Thermometer draus machen ;) Also einen Kreis unten und die bar nach oben, damit man direkt erkennt, was das eigentlich misst. Momentan ist es ja einfach nur eine Kiste

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/AbstractTankDrawer.java
> +        context.fillText(name, outBoxXPos, textYPos);
Bitte ein paar Pixel Abstand zum Rand der Box

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        relValveHeight = ViewConstants.VALVE_HEIGHT / cols;
Größe der Valve sollte sich nach der Höhe richten, weil da zuerst der Platz ausgeht. Die beiden Screenshots wären dann beide behoben
![screenshot_20170221_100452](https://cloud.githubusercontent.com/assets/5811634/23157889/333ffb84-f81d-11e6-8228-d29b7384dec3.png) ![screenshot_20170221_100527](https://cloud.githubusercontent.com/assets/5811634/23157908/47009188-f81d-11e6-972f-54c7decb1eaa.png)

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        relValveHeight = ViewConstants.VALVE_HEIGHT / cols;
Zusätzlich passt irgendwo was mit den Farben nicht, siehe Screenshot

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +                point2yPos + valveHeight - 1);
Mehr Padding von Schrift und Kreis?

2017-02-21 09:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/TemperatureSensorDrawer.java
> +        context.fillRect(tempTopLeftX, tempTopLeftY, tempWidth, tempHeight);
Bisschen Abstand und so ein "Fühler" wie die overflow/underflow sensoren wäre auch gut um klarzumachen, dass das ein Sensor ist

2017-02-21 09:18 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/FillSensorDrawer.java
> +        double compHeight = totalHeight / rows;
Was genau meinst du hier?
Das absolute Verhaeltnis von Hoehe zu Breite? Dann besteht wieder die Gefahr, dass bei manchen Seitenverhaeltnissen des Gesamtfensters Sachen ueberstehen, darum habe ich das (ausser bei Kreisen) vermieden.

2017-02-21 09:19 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        relValveHeight = ViewConstants.VALVE_HEIGHT / cols;
Welche Farben passen nicht?
Die Schrift ist absichtlich blau, um etwas mehr Kontrast/ Lesbarkeit zu geben.

2017-02-21 09:22 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        relValveHeight = ViewConstants.VALVE_HEIGHT / cols;
der mit gelb beschriftete Tank enthält magenta Flüssigkeit. Keine Ahnung, ob der Fehler aus dem Model kommt oder ob hier RGB vertauscht wurden

2017-02-21 09:23 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/FillSensorDrawer.java
> +        double compHeight = totalHeight / rows;
Wenn die sich weiterhin an der Breite richten und ihre Höhe relativ zur Breite festlegen, sollte das kein Problem sein. So ungewöhnlich skaliere nicht mal ich das Fenster (bevor das zu einem Problem wird, sind die Tanks sowieso nicht mehr sichtbar)

2017-02-21 09:28 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/TemperatureSensorDrawer.java
> +        context.fillRect(tempTopLeftX, tempTopLeftY, tempWidth, tempHeight);
Kurz meine paint skills auspacken. So sieht man doch direkt viel klarer, was es für ein Sensor ist
![screenshot_20170221_102718](https://cloud.githubusercontent.com/assets/5811634/23158708/7511ba04-f820-11e6-89de-0da8908176be.png)

2017-02-21 09:33 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        relValveHeight = ViewConstants.VALVE_HEIGHT / cols;
Ich vermute aus dem Model.
Der Name (Zeile 160) kommt mit tank.getTankSelector().getName()

Die Farbe (Zeile 168+) ist rgb mit
tankColor = tank.getLiquid().getColor();
return new Color(tankColor.getR(), tankColor.getG(), tankColor.getB());

Nur im Konstruktor wird ein Tank uebergeben

2017-02-21 09:45 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +        relValveHeight = ViewConstants.VALVE_HEIGHT / cols;
Stimmt, Issue ist erstellt

2017-02-21 09:47 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/FillSensorDrawer.java
> +        double compHeight = totalHeight / rows;
Ist geaendert und pushed

2017-02-21 09:48 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
Eine Menubar klappt sich aber immer aus. Ein Button hat das ausklappen fuer nur ein Menue nicht.

2017-02-21 09:59 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/AbstractTankDrawer.java
> +        context.fillText(name, outBoxXPos, textYPos);
Ist drin

2017-02-21 09:59 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +        primaryStage.setHeight(screenDimensions.getHeight());
Ist drin

2017-02-21 10:02 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
Deshalb auch Ansicht->Steuerung, Datei->Einstellungen, ?->About, ?->Help

So machen das alle anderen Programme auch ;) Oder hast du schon mal ein Programm mit Buttons im Menü benutzt?

2017-02-21 10:04 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
Aktuell kriege ich deine Mails immer in Thunderbird. "write" ist eindeutig ein Button :P

2017-02-21 10:11 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
Hmm das stimmt... Aber in einer Toolbar und mit Icon :D

...was jetzt nicht heißen soll, dass du Icons malen sollst

2017-02-21 10:15 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
Klar.
Ich bin nur tatsaechlich gerade leicht unsicher was du willst.
Laut GUI-Skizze sind die verschiedenen Menues alle oben sichtbar, in unserer TS-Session waren unnoetig viele Ebenen in der Menuefuehrung ein Kritikpunkt, nur ein Button passt auch nicht?
Insofern sieh mich als verwirrt.

2017-02-21 10:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +        buttonSettings = new Button(trans.getString("simulation.view.menu.settings"));
> Ansicht->Steuerung, Datei->Einstellungen, ?->About, ?->Help

So fände ich es gut

2017-02-21 11:44 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ValveDrawer.java
> +                point2yPos + valveHeight - 1);
Der Kreis hat jetzt ein Padding, das der Schrift wuerde ich eher klein lassen. Da finde ich die grosse Schrift von der Lesbarkeit angenehmer als mehr Padding und kleinere Schrift.

2017-02-21 14:21 UTC, ByteHamster approved these changes

2017-02-21 14:22 UTC, merged