[doc] Intro
ByteHamster/PSE pull request #26
Opened 2016-12-03 21:19 UTC by marimbMax

2016-12-04 18:34 UTC, ByteHamster requested changes
Bitte auch noch drauf achten, dass am Zeilenende keine Leerzeichen sind. Ist hier ein paar mal so

2016-12-04 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Dabei hilft das auf Transmission Control Protocol (TCP)/Internet Protocol (IP) basierende Kommunikationsprotokoll OPC Unified Architecture (OPC UA), Maschienen miteinander interagieren zu lassen.
TCP/IP würde ich als glossary machen, nicht inline erklären

2016-12-04 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Dabei hilft das auf Transmission Control Protocol (TCP)/Internet Protocol (IP) basierende Kommunikationsprotokoll OPC Unified Architecture (OPC UA), Maschienen miteinander interagieren zu lassen.
OPC UA genauso

2016-12-04 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +die jeweils eine graphische Benutzeroberfläche (GUI) besitzen und auf getrennten virtuellen Maschinen laufen.
Sie können auf getrennten Maschinen laufen. Müssen nicht. Virtuell würde ich hier weglassen, das ist ja nur unsere Möglichkeit, getrennte Maschinen zu simulieren

2016-12-04 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Drei Tanks werden mit je einer Farbe gefüllt und leiten die Farbe in einen weiteren Tank,
Sie werden mit Flüssigkeit gefüllt, die Farbe hat

2016-12-04 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Die Überwachungskonsole liest die Daten der Fertigungssimulation und stellt sie optisch ansprechend in einem Cockpit dar
und...und...und. Besser Aufzählung mit Komma

2016-12-05 08:03 UTC, Dav1dK submitted a review, later dismissed

2016-12-05 08:03 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +Dabei hilft das auf TCP/IP basierende Kommunikationsprotokoll OPC UA, Maschienen miteinander interagieren zu lassen.
Typo: Maschinen

2016-12-05 08:03 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +wo die Flüssigkeiten durch einen Motor gemischt werden. Daten und Werte des Prozesses werden ebenfalls angezeigt. Dazu gibt es
Ich würde "wo" durch "indem die" ersetzten. Ich finde das klingt besser..

2016-12-05 08:03 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +die Möglichkeit, die Produktion zu konfigurieren, wie zum Beispiel Zu- und Abflussmengen oder Grenzen für Füllstände.
Ich finde der Satz hört sehr überraschend auf, als würde am Ende noch ein Verb fehlen. Mein Vorschlag:
"...die Möglichkeit, die Produktion zu konfigurieren, zum Beispiel in dem man Zu- und Abflussmengen oder Grenzen für Füllstände einstellt."

2016-12-05 08:03 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +Die Überwachungskonsole liest die Daten der Fertigungssimulation, stellt sie optisch ansprechend in einem Cockpit dar
Ich würde Cockpit durch Management Cockpit ersetzten (und diesen Begriff vlt. im Glossar erklären).
Zumindest sagt mit eine kurze Google Suche, dass Cockpit in der Regel das Flugzeugcockpit bezeichnet,
aber unser "Cockpit" normalerweise Managment Cockpit genannt wird.

2016-12-05 09:00 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Die Überwachungskonsole liest die Daten der Fertigungssimulation, stellt sie optisch ansprechend in einem Cockpit dar
Oder wir lassen Cockpit komplett weg, stattdessen Monitoring oder so. Fände ich sowieso besser ;)

2016-12-05 09:41 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +
In der Zeile sind jede Menge Leerzeichen ;)

2016-12-05 18:22 UTC, ByteHamster approved these changes

2016-12-05 18:22 UTC, ByteHamster commented
Würde sagen, nach dem Rebase kann man es dann squashen. Waren ja nur lauter Bugfix Commits

2016-12-05 19:44 UTC, merged