[core/model/base] Reset the model without recreating the objects
ByteHamster/PSE pull request #261
Opened 2017-02-21 18:11 UTC by Dav1dK

Thus the observers of the model don't need to resubscribe to all tanks, pipes and motors.
Also fix a bug, where the motor hasn't notified the observers.

2017-02-21 18:27 UTC, ByteHamster requested changes

2017-02-21 18:27 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +        this.liquid = liquid.clone();
War nicht die Idee hinter einem Datentyp ohne Setter, dass man ihn eben nicht klonen muss? Sollte eigentlich auch ohne gehen, ich meine das Liquid wird ja nicht bearbeitet

2017-02-21 18:27 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Liquid.java
> +            throw new RuntimeException("Error in Color.clone()");
Color? Du machst doch super

2017-02-21 18:27 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Liquid.java
> +            throw new RuntimeException("Error in Color.clone()");
Wirfst du das in Color nicht auch?

2017-02-21 18:27 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public Pipe(float crosssection, int length, byte defaultThreshold) {
Bitte für eine der beiden entscheiden. Sonst taucht irgendwann plötzlich eine 100 auf und keiner weiß, wo sie herkommt

`defaultThreshold = (byte) 100;`

Ich meine das default sollte auf jeden Fall nur an einer Stelle sein. Entweder es wird von außen entschieden oder von innen.

2017-02-21 18:27 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +    protected EnumMap<TankSelector, Float> inputTemperature = new EnumMap<TankSelector, Float>(TankSelector.class);
Final?

2017-02-21 18:27 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                threshold = (byte) 34;
Wah, genau das. Jetzt widerspricht es sich mit dem tank-internen Wert

2017-02-21 18:31 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +            Pipe inPipe = new Pipe(SimulationConstants.PIPE_CROSSSECTION, SimulationConstants.PIPE_LENGTH, threshold);
Ich hab so das Gefühl, dass der Zustand hier nicht ausbalanciert ist. Sollte nicht aus dem unteren Tank 3x so viel ablaufen wie aus den oberen?

2017-02-21 18:33 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +            inputTemperature.put(selector, selector.getInitialTemperature());
Wenn du auf Nummer sicher gehen willst, dass es WIRKLICH zurückgesetzt ist, sollte hier nochmal reset stehen

2017-02-21 18:34 UTC, ByteHamster commented
Wenn du einen bug im Motor behebst, kannst du auch gleich die Farben umsortieren ;)

2017-02-21 18:42 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +        this.liquid = liquid.clone();
Dachte ich auch. Blöderweise kann die Color von Liquid bearbeitet werden. Aber vielleicht kann man das auch ohne Probleme rausnehmen, ich werds mal ausprobieren.

2017-02-21 18:43 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Liquid.java
> +            throw new RuntimeException("Error in Color.clone()");
Ohh, CopyPaste Fehler

2017-02-21 18:44 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public Pipe(float crosssection, int length, byte defaultThreshold) {
Das Problem ist, dass sehr viele Stellen angepasst werden müssen, wenn man den Construktor ändert. Andererseits ist es aber nötig, den defaultThreshold zu setzen damit man die Pipe resetten kann.

2017-02-21 18:45 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                threshold = (byte) 34;
Wie meinst du das?

2017-02-21 18:46 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +        this.liquid = liquid.clone();
Uh stimmt... Das ist ja doof ^^

2017-02-21 18:46 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public Pipe(float crosssection, int length, byte defaultThreshold) {
Muss das wirklich so viel sein? Pipes werden doch eh nur im Model erstellt

2017-02-21 18:46 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +            Pipe inPipe = new Pipe(SimulationConstants.PIPE_CROSSSECTION, SimulationConstants.PIPE_LENGTH, threshold);
Das tut es auch. Die Pipe vom MixTank nach unten hat den Threshold 100, die drei oberen Tanks haben 34 + 33 + 33 = 100.

2017-02-21 18:47 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                threshold = (byte) 34;
Na ja du initialisierst mit 34 und default vom pipe konstruktor ist 100

2017-02-21 18:47 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +            inputTemperature.put(selector, selector.getInitialTemperature());
Stimmt, dann kann ich mir dort ein bisschen was sparen.

2017-02-21 18:47 UTC, Dav1dK commented
Wird gemacht ;)

2017-02-21 18:48 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +            Pipe inPipe = new Pipe(SimulationConstants.PIPE_CROSSSECTION, SimulationConstants.PIPE_LENGTH, threshold);
ah okay. Hab nur nirgends die 100 gesehen auf den ersten Blick. Oder benutzt du da dann das automatische, interne? Falls ja, muss ich mich deutlich dagegen aussprechen :D

2017-02-21 18:52 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +            Pipe inPipe = new Pipe(SimulationConstants.PIPE_CROSSSECTION, SimulationConstants.PIPE_LENGTH, threshold);
Zeile 84, explizit ;)

2017-02-21 19:12 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public Pipe(float crosssection, int length, byte defaultThreshold) {
Hmm stimmt. Habe gerade mal danach gesucht, es werden nur an 23 Stellen Pipes erstellt. Der Compilerfehler sah größer aus :D Dann werde ich das noch ändern.

2017-02-21 19:19 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public Pipe(float crosssection, int length, byte defaultThreshold) {
Normal mag ich solche Änderungen ja nicht, aber in dem Fall wäre es sonst zu inkonsistent

2017-02-21 19:21 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +        this.liquid = liquid.clone();
Ich habe Color immutable gemacht.

2017-02-21 19:23 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/AbstractTank.java
> +        this.liquid = liquid.clone();
Huh und das wirft keine Fehler überall? :D

2017-02-21 19:41 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public Pipe(float crosssection, int length, byte defaultThreshold) {
Ich habe den ersten Konstructor jetzt entfernt.

2017-02-21 19:41 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +    protected EnumMap<TankSelector, Float> inputTemperature = new EnumMap<TankSelector, Float>(TankSelector.class);
Hab ich geändert.

2017-02-21 19:42 UTC, Dav1dK commented
Ich habe Color immutable gemacht, und den ersten Konstruktor von Pipe entfernt. Die anderen Sachen habe ich auch gefixed.

2017-02-21 19:57 UTC, ByteHamster requested changes
Sonst sieht es gut aus

2017-02-21 19:57 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/TankSelector.java
>          return initialColors[this.ordinal()].clone();
Color braucht man nicht mehr klonen

2017-02-21 19:57 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Color.java
>              /* Should never happen */
Dann brauchen wir doch keine clone mehr, oder?

2017-02-21 19:57 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +    final protected EnumMap<TankSelector, Float> inputTemperature = new EnumMap<TankSelector, Float>(TankSelector.class);
Reihenfolge (ist glaub auch im Travis) ist `protected final`

2017-02-21 19:57 UTC, ByteHamster commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/base/TankSelectorTest.java
> +        assertEquals(TankSelector.MAGENTA.getInitialColor(), new Color(0, 1, 0));
Na super auf falsches Verhalten testen hier ^^

2017-02-21 19:57 UTC, ByteHamster commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/behavior/FillAlarmTest.java
> +            30, (byte) 100), new Pipe(200f, 30, (byte) 100));
```
tank = new Tank(200f, TankSelector.valuesWithoutMix()[0], testLiquid, new Pipe(200f,
    30, (byte) 100), new Pipe(200f, 30, (byte) 100));
```
vs
```
tank = new Tank(200f, TankSelector.valuesWithoutMix()[0], testLiquid,
    new Pipe(200f, 30, (byte) 100), new Pipe(200f, 30, (byte) 100));
```

Ich finde, die inneren Klammern sollten nicht umgebrochen werden. Macht es einfacher lesbar

2017-02-21 19:57 UTC, ByteHamster commented on src/osip-model-simulation/src/test/java/edu/kit/pse/osip/core/model/simulation/MixTankSimulationTest.java
> +        MixTankSimulation tank = new MixTankSimulation(1000, content, new Pipe(10, 10,
Ich finde, die inneren Klammern sollten nicht umgebrochen werden. Macht es einfacher lesbar

2017-02-22 10:49 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Color.java
>              /* Should never happen */
Eigentlich nicht.

2017-02-22 10:54 UTC, Dav1dK commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/behavior/FillAlarmTest.java
> +            30, (byte) 100), new Pipe(200f, 30, (byte) 100));
Ich habe die Pipes in attribute ausgelagert.

2017-02-22 11:01 UTC, Dav1dK commented on src/osip-model-simulation/src/test/java/edu/kit/pse/osip/core/model/simulation/MixTankSimulationTest.java
> +        MixTankSimulation tank = new MixTankSimulation(1000, content, new Pipe(10, 10,
Habe ich ebenfalls ausgelagert.

2017-02-22 11:23 UTC, ByteHamster requested changes

2017-02-22 11:23 UTC, ByteHamster commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/base/TankSelectorTest.java
> +     * Check whether getIntialColor() and getInitialTemperatue/( returns a value for every tank. Should not throw an
Falsche Klammern ;) `/(`

2017-02-22 11:23 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Tank.java
> +    public void reset() {
Wäre es nicht sinnvoll, wenn die synchronized wären?

2017-02-22 16:02 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Tank.java
> +    public void reset() {
Stimmt, sollte so sein.

2017-02-22 16:07 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Motor.java
> +    }
Bei allen anderen nimmst du die Parameter aus dem Konstruktor zum reset. Dann solltest du es hier auch machen, um konsistent zu sein

2017-02-23 10:51 UTC, ByteHamster approved these changes

2017-02-23 14:30 UTC, merged