[monitoring/view/dialogs]  About Controller Rework
ByteHamster/PSE pull request #264
Opened 2017-02-22 15:21 UTC by marimbMax

2017-02-22 18:39 UTC, ByteHamster requested changes

2017-02-22 18:39 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MenuAboutButtonHandler.java
> +        d.show();
Das reduziert die lose Koppelung zwischen UI und Controller. Konkrete view instanzen bitte nur im konstruktor vom controller erstellen

2017-02-22 18:39 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentProductionSite = new ProductionSite();
Warum?

2017-02-22 18:39 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dialogs/AboutDialog.java
> +}
Newline

2017-02-22 18:40 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MenuAboutButtonHandler.java
> +        d.show();
Vielleicht auch wie jetzt neu im Controller auf Lambdas setzen

2017-02-22 18:53 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentProductionSite = new ProductionSite();
Das war vorher so und ich habs geändert, um meinen dialog zu testen. Dann hab ichs zurückgeändert.

2017-02-22 19:09 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentProductionSite = new ProductionSite();
Wenn du es wieder so gemacht hättest wie es war, würde es doch keine Änderung anzeigen ;)

2017-02-22 19:12 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentProductionSite = new ProductionSite();
https://github.com/ByteHamster/PSE/blob/master/src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java#L42

2017-02-22 19:15 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentProductionSite = new ProductionSite();
Oh, es wäre besser gewesen, ich hätte mir aufgeschrieben, was ich geändert habe ^^

2017-02-22 19:17 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentProductionSite = new ProductionSite();
Na ja sieht man doch am Diff :) Gerade dafür ist er ja da

2017-02-23 16:25 UTC, ByteHamster requested changes

2017-02-23 16:25 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentSettingsView.setSettingsSaveButtonHandler(new SettingsSaveButtonHandler(currentSettings,
Sieht recht gut aus. Bitte die Kommentare raus löschen und den Parameter vom Lambda umbenennen. Da steht momentan EventHandler als wäre es eine Klasse. Stattdessen müsste da einfach event stehen, weil dem Lambda ein Event übergeben (und nicht genutzt) wird.

2017-02-23 16:26 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentSettingsView.setSettingsSaveButtonHandler(new SettingsSaveButtonHandler(currentSettings,
Ach ja und Checkstyle scheint sich nicht zu beschweren... Aber ich hab Lambdas bisher nur mir Leerzeichen um den Pfeil gesehen

2017-02-23 16:58 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        currentSettingsView.setSettingsSaveButtonHandler(new SettingsSaveButtonHandler(currentSettings,
Das ist noch nicht fertig. Habs nur als Sicherheitskopie gepusht.

2017-02-23 19:30 UTC, ByteHamster requested changes

2017-02-23 19:30 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties
> +monitoring.aboutdialog.aboutIntroduction=OSIP is a PSE project, which was created in 2016/2017 by five students of the KIT.
Ich glaube vor `which` gehört kein Komma

2017-02-23 19:30 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties
> +monitoring.aboutdialog.license=The MIT License\n\nCopyright (c) 2016\nDavid Kahles\nHans-Peter Lehmann\nMartin Armbr\u00FCster\nMaximilian Schwarzmann\nNiko Wilhelm\n\nPermission is hereby granted, f
Martin schreibt man nicht mit `ü`

2017-02-23 19:30 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dialogs/AboutDialog.java
> +        Image imageIcon = new Image(getClass().getClassLoader().getResourceAsStream("icon.png"));
Es wäre cool, wenn rechts neben dem Icon nochmal groß `OSIP` stehen würde

2017-02-23 19:30 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties
> +monitoring.aboutdialog.license=The MIT License\n\nCopyright (c) 2016\nDavid Kahles\nHans-Peter Lehmann\nMartin Armbr\u00FCster\nMaximilian Schwarzmann\nNiko Wilhelm\n\nPermission is hereby granted, f
Der Text sollte meiner Meinung nach nicht manuell umgebrochen werden, sondern sich an der Breite des Fensters orientieren.

2017-02-23 20:04 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties
> +monitoring.aboutdialog.aboutIntroduction=OSIP is a PSE project, which was created in 2016/2017 by five students of the KIT.
Da sollte ein Komma sein, weil der Nebensatz nicht unbedingt notwendig ist für das Verständnis.

2017-02-23 20:13 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/resources/Bundle.properties
> +monitoring.aboutdialog.aboutIntroduction=OSIP is a PSE project, which was created in 2016/2017 by five students of the KIT.
okay

2017-02-24 21:54 UTC, ByteHamster approved these changes

2017-02-24 21:58 UTC, merged