Simulation view control
ByteHamster/PSE pull request #265
Opened 2017-02-22 16:55 UTC by NikoWil

Das Fenster zur Steuerung der Simulation.

2017-02-22 18:46 UTC, ByteHamster requested changes

2017-02-22 18:46 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        this.setContent(this.getGridPane());
Bitte hier pane übergeben. Auch wenn es eigentlich das gleiche sein sollte, ist es verwirrend

2017-02-22 18:46 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        this.setContent(pane);
Ah hier setzt du direkt die Pane. So finde ich es deutlich verständlicher als oben

2017-02-24 21:28 UTC, ByteHamster commented
- [ ] Temperatur-Textboxen
- [ ] Celsius (Model oder umrechen)

2017-02-27 19:38 UTC, HansMartinA requested changes

2017-02-27 19:38 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    private int row;
Ich hätte hier row auf protected gestellt und so aus den Unterklassen direkt darauf zugegriffen. Dann müssen diese nicht nochmal row speichern und über eine get-Methode den aktuellen Wert auslesen.

2017-02-27 19:38 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    private void createTemperatureSlider(GridPane pane, AbstractTank tank) {
Die Übergabe vom GridPane ist hier unnötig, da du auf das GridPane pane aus der Klasse zugreifst.

2017-02-27 19:38 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    private void createOutFlowSlider(GridPane pane, AbstractTank tank) {
Hier ist die Übergabe von GridPane ebenfalls nicht notwendig.

2017-02-27 19:38 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +public abstract class AbstractTankTab extends Tab {
Für sämtliche Zahlen in dieser Klasse gilt: Bitte Konstanten benutzen!

2017-02-27 19:38 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +public class MixTankTab extends AbstractTankTab {
Für sämtliche Zahlen in dieser Klasse gilt: Bitte Konstanten benutzen!

2017-02-27 19:38 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +public class TankTab extends AbstractTankTab {
Für sämtliche Zahlen in dieser Klasse gilt: Bitte Konstanten benutzen!

2017-02-28 07:24 UTC, ByteHamster requested changes
+ rebase

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/resources/Bundle.properties
> +simulation.control.title=Control
Newline

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        float min = SimulationConstants.MIN_TEMPERATURE - 273.15f;
Konstante

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    protected void connectElements(Slider slider, TextField textField, boolean isIntegerValue) {
Da gibt es direkt in javafx eine bidirektionale Verbindung. Bitte Bordmittel nutzen. Für ein Beispiel zu Martin in die Settings schauen

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +            SimulationControlWindow window = new SimulationControlWindow(new ProductionSite());
Deine View sollte keine Fenster starten. Das macht der Controller

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_INPUT_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.034;
Das ist keine gute Möglichkeit. Je nach Auflösung werden die sehr klein. Bitte entweder an der Breite der Schrift orientieren oder konstant wählen, sodass es für die Schrift passt.

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Der sollte sich nach der Fensterbreite richten

2017-02-28 07:24 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +
Lass die lieber weg. Führt nur zu Konflikten mit deinen anderen PR, sobald einer davon gemerged ist

2017-02-28 07:42 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_INPUT_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.034;
Die Schrift ist doch auch ueber eine Konstante festgelegt, die sich am Screen orientiert?

Zumindest sollten die also immer zusammen passen. Ich kann es aber auch gleich an der anderen Konstanten festmachen...

2017-02-28 07:43 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Macht er jetzt doch?

2017-02-28 07:43 UTC, NikoWil commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +
Das sind die, die schon drin waren die ich dann mit verschoben hab. Neu erstellt hab ich die nicht.

2017-02-28 07:45 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +
Ich meinte die leere Zeile

2017-02-28 07:46 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Dann brauchst du ihn aber nicht mehr abhängig von der Bildschirmbreite initialisieren

2017-02-28 07:47 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_INPUT_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.034;
Dann lieber an der anderen, ja

2017-02-28 08:50 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Sorry, ich meinte abhaengig von der Bildschrimbreite.
Das Controlwindow hat ja keine fest Breite, die orientiert sich an den enthaltenen Komponenten.

2017-02-28 08:52 UTC, NikoWil commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +
Ist auf origin/master Stand zurueckgesetzt.

2017-02-28 08:52 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Das sollte sich aber ans Fenster richten, damit man es ordentlich skalieren kann. Ist eh nur eine zusätzliche Zeile Code (siehe hscale vom gridpane)

2017-02-28 08:55 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +    public final void setTank(TankSelector tank) {
Wenn du das auf master zurücksetzt, solltes du keine merge konflikte bekommen

2017-02-28 08:58 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_INPUT_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.034;
Jetzt ist es an der Schriftgroesse. So, dass immer 6 Stellen reinpassen, dann sind es durchgehend 3 Nachkommastellen die angezeigt werden

2017-02-28 08:58 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    protected void connectElements(Slider slider, TextField textField, boolean isIntegerValue) {
Wird jetzt genutzt.

2017-02-28 09:01 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMenu.java
> +            SimulationControlWindow window = new SimulationControlWindow(new ProductionSite());
Wieder auf origin/master Stand.

2017-02-28 09:10 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Wo hat Gridpane ein hscale? (strg+f in der API ergibt nichts)

2017-02-28 09:13 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
ups heißt hgrow

2017-02-28 09:25 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/ViewConstants.java
> +    public static final double CONTROL_SLIDER_WIDTH = Screen.getPrimary().getBounds().getWidth() * 0.3;
Jep, hatte es auch gerade gefunden.
Die Slider schnappen sich jetzt allen zusaetzlichen Platz. Der Rest profitiert davon ja nicht.

2017-02-28 09:30 UTC, HansMartinA requested changes

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        Label temperatureLabel = new Label(t.getString("simulation.view.temperatureLabel"));
Hier fehlt noch das Margin für den Label.

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        Label outFlowLabel = new Label(t.getString("simulation.view.outFlowLabel"));
Hier fehlt noch das Margin für den Label.

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        Label motorLabel = new Label(t.getString("simulation.view.motorLabel"));
Hier fehlt noch das Margin für den Label.

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        Label inFlowLabel = new Label(t.getString("simulation.view.inFlowLabel"));
Hier fehlt noch das Margin für den Label.

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        inFlowSlider.setMajorTickUnit(10);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        inFlowSlider.setMinorTickCount(9);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        motorSlider.setMajorTickUnit(SimulationConstants.MAX_MOTOR_SPEED / 10);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        motorSlider.setMinorTickCount((SimulationConstants.MAX_MOTOR_SPEED / 10) - 1);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider.setMajorTickUnit(10);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider.setMinorTickCount(9);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider = new Slider(0, 100, tank.getOutPipe().getValveThreshold());
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        temperatureSlider.setMajorTickUnit(25);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        temperatureSlider.setMinorTickCount(9);
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        inFlowSlider = new Slider(0, 100, tank.getOutPipe().getValveThreshold());
Bitte hier auch Konstanten benutzen!

2017-02-28 09:30 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +public class OverflowDialog extends Stage {
Warum genau ist die Klasse hier?

2017-02-28 09:38 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider = new Slider(0, 100, tank.getOutPipe().getValveThreshold());
Haben wir irgenwo Konstanten dafuer? Die hatte ich noch nicht gesehen. Oder dann im Model da auch noch neue einfuehren?

2017-02-28 09:38 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider.setMajorTickUnit(10);
Siehe bei dem oberen.

2017-02-28 09:40 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        motorSlider.setMajorTickUnit(SimulationConstants.MAX_MOTOR_SPEED / 10);
Wuerde ich eher vom MOTOR_SPEED abhaengig halten. Dann ist die Anzahl an Labels immer gleich. Sonst stehen manche Zahlen so dicht nebeneinander, dass nicht klar ist welche welche ist.

2017-02-28 09:41 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider = new Slider(0, 100, tank.getOutPipe().getValveThreshold());
Nein, das haben wir für diese nicht. Aber wie mir gerade auffällt, ist das Prozent. Von daher ist es hier doch nicht unbedingt notwendig.

2017-02-28 09:42 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider.setMajorTickUnit(10);
https://github.com/ByteHamster/PSE/blob/master/src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/MonitoringViewConstants.java#L61

In der Simulation nicht, aber in der Überwachungskonsole.

2017-02-28 09:44 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        motorSlider.setMajorTickUnit(SimulationConstants.MAX_MOTOR_SPEED / 10);
Ich habe die Labels auch von den Konstanten abhängig gemacht, aber auch die Zahl der Labels als Konstante festgelegt.

2017-02-28 09:49 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider.setMajorTickUnit(10);
Ich finds aber gar nicht sooo sinvoll, fuer alle Slider die Werte da gleich zu halten. Gerade bei flow bietet sich ja 1 Tick/ Einheit an, es sind ja immer 100.

Temperatur und Motor haben da ja ganz andere Wertebereiche

2017-02-28 09:52 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        outFlowSlider.setMajorTickUnit(10);
Ich sage ja nicht, dass die Werte für alle Slider gleich sein sollen. Aber Werte für mehrere Slider sollten schon als Konstanten herausgezogen werden, finde ich.

2017-02-28 10:09 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        Label inFlowLabel = new Label(t.getString("simulation.view.inFlowLabel"));
Margin ist drin.

2017-02-28 10:09 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        Label motorLabel = new Label(t.getString("simulation.view.motorLabel"));
Margin ist drin.

2017-02-28 10:09 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        Label outFlowLabel = new Label(t.getString("simulation.view.outFlowLabel"));
Margin ist drin.

2017-02-28 10:09 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +        Label temperatureLabel = new Label(t.getString("simulation.view.temperatureLabel"));
Margin ist drin.

2017-02-28 10:37 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +public class TankTab extends AbstractTankTab {
Ich glaube ich hab jetzt alle

2017-02-28 10:38 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +public class MixTankTab extends AbstractTankTab {
Ich glaube ich hab jetzt alle.

2017-02-28 10:39 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +public abstract class AbstractTankTab extends Tab {
Sollten jetzt alle sein.

2017-02-28 10:59 UTC, HansMartinA approved these changes

2017-02-28 13:01 UTC, ByteHamster approved these changes

2017-02-28 13:02 UTC, merged