[simulation/view/dialogs] Simulation overflow dialog
ByteHamster/PSE pull request #272
Opened 2017-02-25 12:48 UTC by marimbMax

Nicht endgültig. Bitte nur design und code vom OverFlowDialog reviewen. Da ist noch code dabei, der nur das ganze testbar macht und nachher gelöscht wird.

2017-02-25 13:30 UTC, HansMartinA requested changes
Ist mir als erstes ins Auge gefallen. Den Rest schaue ich mir später an.

2017-02-25 13:30 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/MainClass.java
> +        con.launch(SimulationController.class, args);
Der Aufruf hier ist unnötig. Es reicht Application.launch(SimulationController.class, args), da das ein statischer Aufruf ist.

2017-02-25 13:35 UTC, marimbMax commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/MainClass.java
> +        con.launch(SimulationController.class, args);
Wie gesagt, das wird später eh wieder gelöscht.

2017-02-25 18:50 UTC, ByteHamster requested changes

2017-02-25 18:50 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        if (tank != null) {
Würde hier eher eine IllegalStateException werfen und sagen, dass man vor dem Anzeigen doch bitte den Tank setzen soll

2017-02-25 20:50 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +            throw new IllegalStateException("No tank is set, where the overflow occured.");
Würde das genauer beschreiben. "No tank set. Please call setTank() before calling show()" oder so.

2017-02-25 21:11 UTC, marimbMax commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +            throw new IllegalStateException("No tank is set, where the overflow occured.");
Mist, das hatte ich an Anfang, habs aber gelöscht, weil ich dachte, dass du sagen würdest, es wäre unnötig ^^

2017-02-26 09:52 UTC, ByteHamster commented
Hier bitte ebenso Controller und mainClass nicht bearbeiten

2017-02-26 10:19 UTC, HansMartinA submitted a review, later dismissed

2017-02-26 10:19 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        configure();
Bitte entfernen! Das führt immer zu einer Exception.
Oder vielleicht nur einen Konstruktor mit TankSelector als Parameter, also OverflowDialog(TankSelector), anbieten. Damit würde sich der Aufruf der setTank Methode erübrigen.

2017-02-26 10:19 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +    public final void setTank(TankSelector tank) {
Hier finde ich eine NullPointerException sinnvoll, wenn der Tank null ist. Ansonsten kommt es zur IllegalStateException, die sagt, rufe die Methode setTank auf, obwohl man diese aufruft.

2017-02-26 10:19 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        grid.setHgrow(overflowTextFlow, Priority.ALWAYS);
Das hier ist auch ein statischer Aufruf. Daher empfehle ich hier, diesen auch auf GridPane direkt zu machen. Ich denke, es bietet sich auch an, den Aufruf unter die Aufrufe in Zeile 72 und 73 zu stellen.

2017-02-26 10:19 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +
Fehlt hier nicht noch der Reset-Knopf?

2017-02-26 22:44 UTC, marimbMax commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        configure();
Was genau entfernen ?

2017-02-26 22:44 UTC, marimbMax commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        grid.setHgrow(overflowTextFlow, Priority.ALWAYS);
Wieso macht das einen Unterschied ?

2017-02-26 23:54 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        configure();
Der configure()-Aufruf. Wenn ich einen neuen OverflowDialog erstelle, kommt so direkt die IllegalStateException, die mir sagt, dass ich doch die setTank Methode aufrufen soll. Das kann ich aber nicht, wenn ich das Objekt erst erstelle.

2017-02-26 23:55 UTC, HansMartinA commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/dialogs/OverflowDialog.java
> +        grid.setHgrow(overflowTextFlow, Priority.ALWAYS);
Ich finde, dass dann alle Aufrufe, die den overflowTextFlow betreffen, an einem Ort gebündelt sind und das ganze übersichtlicher machen. Ist zumindest mein Empfinden.

2017-02-27 22:23 UTC, ByteHamster approved these changes

2017-02-27 22:23 UTC, merged