[simulation/controller] Implement simulation controller
ByteHamster/PSE pull request #274
Opened 2017-02-25 15:56 UTC by Dav1dK

2017-02-25 18:45 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/PhysicsSimulator.java
> +        productionSite.setInputTemperature(tank, temperature);
Ich glaub die Funktion wird nirgends benutzt

2017-02-25 18:45 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +    private static final int DEFAULT_PORT = 12686;
Die Konstante bitte irgendwo zentral speichern und an den anderen Stellen löschen

https://github.com/ByteHamster/PSE/blob/master/src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/GeneralSettings.java#L109

https://github.com/ByteHamster/PSE/blob/master/src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/settings/SimulationSettingsWindow.java#L119

2017-02-25 18:45 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            settingsWrapper = new ServerSettingsWrapper(new File("file"));
Da müsste Max noch die Settings anpassen und die Exception entfernen

2017-02-25 18:45 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        settingsInterface.setSettingsChangedListener(this::reSetupServer);
Die Settings speichern es momentan noch nicht automatisch in den Wrapper ab, soweit ich weiß.

2017-02-25 18:45 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +    private class MixTankContainer {
Auch ein kurzer Kommentar wäre gut

2017-02-26 11:17 UTC, HansMartinA requested changes

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            settingsWrapper = new ServerSettingsWrapper(new File("file"));
Was soll "file" für eine Datei sein? Ich hätte hier eine Standarddatei eingefügt, damit das Programm starten kann!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            cont.overflowAlarm = new FillAlarm(cont.tank, 95f, AlarmBehavior.GREATER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            cont.underflowAlarm = new FillAlarm(cont.tank, 5f, AlarmBehavior.SMALLER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            cont.overheatAlarm = new TemperatureAlarm(cont.tank, 5000f, AlarmBehavior.GREATER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            cont.undercoolAlarm = new TemperatureAlarm(cont.tank, 200f, AlarmBehavior.SMALLER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        mixCont.overflowAlarm = new FillAlarm(mixCont.tank, 95f, AlarmBehavior.GREATER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        mixCont.underflowAlarm = new FillAlarm(mixCont.tank, 5f, AlarmBehavior.SMALLER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        mixCont.overheatAlarm = new TemperatureAlarm(mixCont.tank, 5000f, AlarmBehavior.GREATER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        mixCont.undercoolAlarm = new TemperatureAlarm(mixCont.tank, 200f, AlarmBehavior.SMALLER_THAN);
Konstanten!

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +    public void startMainLoop() {
Warum ist diese Methode public?

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +public class SimulationController extends Application {
Vielleicht geht's nur mir so, aber ich finde die Reihenfolge der Methoden unintuitiv und hätte sie anders sortiert (SimulationController(), setupServer(), reSetupServer(), setupAlarms(), startMainLoop(), updateServerValues(), start(), setupView(), stop()).

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +                cont.server = new TankServer(settingsWrapper.getServerPort(cont.selector, defaultPort++));
Müsste nicht anschließend noch ein old.stop() kommen, da ansonsten die Server einfach weiterlaufen?

2017-02-26 11:17 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            mixCont.server = new MixTankServer(defaultPort);
Hier auch ein old.stop()?

2017-02-27 12:23 UTC, Dav1dK commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +            settingsWrapper = new ServerSettingsWrapper(new File("file"));
Das war nur zum testen. Aber welche Standarddatei? Soll ja auf Linux wie auf Windows Sinn ergeben.

2017-02-27 12:44 UTC, Dav1dK commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +    public void startMainLoop() {
Weil sie im Entwurf public ist. Aber ich kann sie auch private machen.

2017-02-27 15:20 UTC, Dav1dK commented
Alle Kritikpuntke sollten gefixt sein. Passt euch der Name des Configfiles?

2017-02-27 15:46 UTC, ByteHamster commented
Pfad finde ich okay

2017-02-27 16:22 UTC, ByteHamster reviewed
Sieht recht gut aus vom ersten Anschauen. Ich würde noch auf das control window warten, bevor wir das mergen

2017-02-27 16:22 UTC, ByteHamster commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/OSIPConstants.java
> + * Some constants which are used in multiple places but doesn't bbelong into the model
`doesn't bbelong` ==> `don't belong` (sg/pl vermischt)

2017-02-27 16:22 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                count++;
Count++ würde ich in jedem Durchlauf zählen. Sollte auch so funktionieren, aber ein count, der dann irgendwann aufhört, ist seltsam

2017-02-27 16:22 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/PhysicsSimulator.java
> +        productionSite.setInputTemperature(tank, temperature);
Bitte löschen, wenn das wirklich so ist

2017-02-27 18:58 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                count++;
Von mir aus, ich dachte das spart ein kleines bisschen Performance, aber das ist wirklich vernachlässigbar

2017-02-27 19:00 UTC, Dav1dK commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/PhysicsSimulator.java
> +        productionSite.setInputTemperature(tank, temperature);
Ich hab die Funktion jetzt benutzt, siehe SimulationController.java:237.

2017-02-27 19:08 UTC, HansMartinA submitted a review, later dismissed

2017-02-27 19:08 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        new File(System.getProperty("user.home") + "/.osip").mkdir();
Zur Plattformunabhängigkeit eignet sich hier statt "/" File.separator zu nehmen.

2017-02-27 19:08 UTC, HansMartinA commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/behavior/FillAlarmTest.java
> +        alarm = new FillAlarm(tank, 0.5f, AlarmBehavior.GREATER_THAN);
Ich finde, hier ist es besser, auch Konstanten zu benutzen. Damit hättest du nicht x-mal die Werte ändern müssen, sondern nur einmal.

2017-02-27 19:09 UTC, HansMartinA commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +    public void startMainLoop() {
Soweit ich weiß, wird sie nicht von außen aufgerufen. Damit gibt es keinen Grund, dass sie public ist.

2017-02-27 19:38 UTC, ByteHamster commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                count++;
Du mit deinen Performance Sachen ^^ Also bevor du sowas machst, dann lieber die OPC UA Sachen nur bei Änderungen setzen :P Das würde mehr helfen

2017-02-27 20:17 UTC, ByteHamster commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        new File(System.getProperty("user.home") + "/.osip").mkdir();
Wenn du es übrigens so machst, steht da nicht zweimal der gleiche Pfad

```
File settingsLocation = new File(System.getProperty("user.home") + File.separator + ".osip");
settingsLocation.mkdirs();
currentSettings = new ClientSettingsWrapper(new File(settingsLocation, "monitoring.conf"));
```

2017-02-28 18:38 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/ProductionSite.java
> +                count++;
Also gut, dann mach ich es halt in jedem Durchlauf^^

2017-02-28 18:41 UTC, Dav1dK commented on src/osip-simulation-controller/src/main/java/edu/kit/pse/osip/simulation/controller/SimulationController.java
> +        new File(System.getProperty("user.home") + "/.osip").mkdir();
Wird gemacht

2017-02-28 18:42 UTC, Dav1dK commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/behavior/FillAlarmTest.java
> +        alarm = new FillAlarm(tank, 0.5f, AlarmBehavior.GREATER_THAN);
Finde ich nicht nötig und auch nicht so gut, weil die Liquids in jedem Test neu (und unterschiedlich) erzeugt werden. Denn wenn man die Alarmschwelle ändert, muss man auch oft die Liquids anpassen.

2017-02-28 21:46 UTC, HansMartinA commented
Wenn ich das Ding ausführe, kommen folgende Fehler vor:
- [ ] Die Temperaturslider im Control triggern keine Updates für die Temperaturanzeigen in der Simulation.
- [ ] Wenn es zu einem Overflow kommt, wird das Fenster angezeigt. Wenn ich dann im Control irgendetwas umstelle, d. h. Werte ändere, wird immer wieder ein neues Overflow-Fenster angezeigt.
- [ ] Bei einem Reset wird zwar das Model und die Ansicht zurückgesetzt, aber das Control nicht. Auch ein Neustart des Controls, d. h. Schließen und erneut Öffnen, ändert nichts.
- [ ] Der Start von OPC UA dauert unter Windows extrem lange (bis zur Anzeige des Fensters bei mir etwa 1 min. und es liegt nicht am Computer), weswegen ein Neustart der Server zu einem Einfrieren der GUI führt.

2017-02-28 22:08 UTC, ByteHamster commented
> Die Temperaturslider im Control triggern keine Updates für die Temperaturanzeigen in der Simulation.

Doch, tun sie. Die Anzeige ist aber kaputt (geht nur ab 150°) und es dauert eine Weile, bis sich die Temperatur anpasst. Anzeige wird in #293 behoben

> Bei einem Reset wird zwar das Model und die Ansicht zurückgesetzt, aber das Control nicht. Auch ein Neustart des Controls, d. h. Schließen und erneut Öffnen, ändert nichts.

Das muss Niko im control window beheben. Issue ist erstellt #294

2017-02-28 22:11 UTC, ByteHamster commented
> Wenn es zu einem Overflow kommt, wird das Fenster angezeigt. Wenn ich dann im Control irgendetwas umstelle, d. h. Werte ändere, wird immer wieder ein neues Overflow-Fenster angezeigt.

Da muss Niko noch eine disable methode hinzufügen, die die ganzen Slider deaktiviert. Auch in #294

2017-03-01 10:44 UTC, ByteHamster approved these changes

2017-03-01 10:48 UTC, merged