Simulation control fix
ByteHamster/PSE pull request #299
Opened 2017-03-01 14:11 UTC by NikoWil

Die Steuerungselemente der Simulation koennen jetzt deaktiviert werden.
Die Steuerungselemente observen ihre jeweiligen Tanks, um Aenderungen zu uebernehmen.
Es gibt einen reset-button im Menue.

2017-03-01 14:36 UTC, ByteHamster requested changes

2017-03-01 14:36 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +        super.update(observable, o);
Bitte als erstes Statement

2017-03-01 14:36 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +        super.update(observable, o);
Ebenso

2017-03-01 14:36 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
Bitte nicht das Encoding kaputt machen. Das muss ISO-85xy bleiben, damit der Translator funktioniert

2017-03-01 14:37 UTC, NikoWil commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
Wie wird es sonst eingetragen?
Ich hab es wieder damit ersetzt, da mein IntelliJ es durch ein ? ersetzt hat und das dann natuerlich commiten wollte...

2017-03-01 14:42 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
Du kannst in Intellij einstellen, welches Encoding resource files haben sollen

2017-03-01 14:44 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
Außerdem glaube ich, dass du das "?" einfach hättest lassen können. Dann hätte es da nichts geändert

2017-03-01 14:45 UTC, NikoWil commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
Doch. Das ist mir im git diff aufgetaucht. Also als ?, nicht das unbekanntes Zeichen Symbol

2017-03-01 14:46 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
Okay dann halt umstellen oder einen anderen Editor dafür nehmen

2017-03-01 14:52 UTC, NikoWil commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
ISO 85 oder ISO 88? Letzteres kennt mir IntelliJ, ersteres nicht

2017-03-01 14:56 UTC, ByteHamster commented on src/osip-simulation-view/src/main/resources/Bundle.properties
> +simulation.view.temperatureUnit=°C
8859-1

2017-03-01 15:16 UTC, NikoWil commented
Nicht mergen bis die Frage der TemperatureSlider geklaert ist (Issue 294)

2017-03-01 18:04 UTC, ByteHamster commented
Die Regler müssen bei einem Overflow deaktiviert werden. Sonst gibt es jede Menge overflow dialoge
![image](https://cloud.githubusercontent.com/assets/5811634/23473805/d14627d2-feb1-11e6-9f15-2e9809b61b42.png)

2017-03-02 10:14 UTC, ByteHamster approved these changes

2017-03-02 10:14 UTC, merged