A different approach to the slider update problem
ByteHamster/PSE pull request #306
Opened 2017-03-03 17:42 UTC by Dav1dK

Let the tank tabs register the listener and have a attribute which
tracks wether the model update is because of the slider, to ignore it.
This means that the model recieves updates all the time, except when the
updates are by itself. This is different than before, because before the
window had only recieved updates, if the control elements were disabled.

Additionally, improve some other small things.

2017-03-04 09:06 UTC, ByteHamster reviewed
Funktioniert bei mir

2017-03-04 09:06 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    void setValveListener(BiConsumer<Pipe, Byte> listener) {
Würde protected schreiben

2017-03-04 09:06 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/MixTankTab.java
> +    void setMotorListener(Consumer<Integer> listener) {
Protected?

2017-03-04 09:06 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +    void setValveListener(BiConsumer<Pipe, Byte> listener) {
Protected

2017-03-04 09:06 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/TankTab.java
> +    void setTemperatureListener(BiConsumer<TankSelector, Float> listener) {
Protected

2017-03-04 11:45 UTC, NikoWil requested changes
Funktioniert bei mir.
Allerdings ist mir noch ein Fehler aufgefallen (der auch vorher offenbar schon da war): wird ein Szenario gestartet und kommt es innerhalb oder nach dem Szenario zu einem Ueberlauf werden die Steuerelemente nicht geblockt und es kann wieder zum oeffnen sehr vieler OverFlowDialoge fuehren.

Ich suche noch nach einem Fix und wuerde den dann auch hier mit einbauen.

Problem gefunden:
Ausgangssituation: im SimulationController ist currentScenario != null
showOverflow wird aufgerufen
in der Methode in Zeile 223 ist die Bedingung wahr
Zeile 225 ruft currentSimulationView.scenarioFinished() auf

SimulationMainWindow.scenarioFinished() ruft in Zeile 252 menu.setScenarioFinished() auf

SimulationMenu.setScenarioFinished() aktiviert in Zeile 169 die Kontrollen

Moegliche Fixes:
- Wir koennen unterscheiden zwischen ScenarioFinished und ScenarioAborted und fuegen fuer letzteres neue Methoden ein, um es sauber zu trennen. Verursacht aber deutlich Overhead.
- Im SimulationController showOverflow aendern wir die Reihenfolge von <Kontrollen deaktivieren, Dialog anzeigen, Szenario beenden> zu <Szenario beenden, Kontrollen deaktivieren, Dialog anzeigen>. Dann besteht zwar die Gefahr, dass die Kontrollen fuer einen winzigen Moment aktiviert sind, allerdings ist zu dem Zeitpunkt garantiert noch kein Dialog in der Anzeige, sollte also gefahrlos sein.

2017-03-04 14:36 UTC, Dav1dK commented
Warum lassen wir nicht die Zeile 169 im SimulationMenu weg, die die Kontrollen aktiviert? Ich finde das gehört dort sowieso nicht hin. Diese Methode sollte sich nur um das Menu kümmern, schließlich ist es ja in der Datei SimulationMenu.java. Wenn die Kontrollen aktiviert werden müssen, dann sollte das doch der SimulationController machen können, oder?

2017-03-04 14:38 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    void setValveListener(BiConsumer<Pipe, Byte> listener) {
Intellij schlägt hier (und bei den anderen Kommentaren) Package Private vor, was ja auch Sinn macht, da es noch eingeschränkter ist. Soll ich es trotzdem ändern?

2017-03-04 14:40 UTC, ByteHamster commented
Hatte mich auch ein bisschen gewundert, dass man das control window mit ins Menü schleppen muss

2017-03-04 15:41 UTC, Dav1dK commented
Ich habe das mal implementiert.

2017-03-05 11:53 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    void setValveListener(BiConsumer<Pipe, Byte> listener) {
Ich weiß... Sieht finde ich trotzdem immer aus, als hätte man es vergessen :D

2017-03-05 17:17 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/control/AbstractTankTab.java
> +    void setValveListener(BiConsumer<Pipe, Byte> listener) {
Na gut, von mir aus..

2017-03-05 17:34 UTC, NikoWil approved these changes

2017-03-05 17:41 UTC, merged