[monitoring/controller] Monitoring Controller Preview
ByteHamster/PSE pull request #307
Opened 2017-03-03 22:31 UTC by marimbMax

2017-03-04 12:12 UTC, ByteHamster submitted a review, later dismissed

2017-03-04 12:12 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/AbstractSettingsSaveButtonHandler.java
> +public abstract class AbstractSettingsSaveButtonHandler implements EventHandler<ActionEvent> {
Handler hatten wir entfernt. Bitte keine neuen mehr einbauen

2017-03-04 12:12 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    case 1: System.err.println("The client disconnected from the server!");
Hier bitte die Konstanten benutzen, die ich definiert hab

2017-03-04 12:12 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    client.subscribeFillLevel(-1,
Da wäre es vielleicht noch sinnvoll, eine Konstante in meine Klasse einzubauen. Sonst sieht die -1 seltsam aus. Besser: UAClientWrapper.SINGLE_READ oder so

2017-03-04 12:12 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    case 1: System.err.println("The client disconnected from the server!");
Konstanten ;)

2017-03-04 12:12 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +    private class MixTankContainer {
Die Container haben sehr viel gemeinsam. Bitte gemeinsame Oberklasse basteln und die einzelnen erben

2017-03-04 14:08 UTC, HansMartinA requested changes
Der Teil, den ich dir bereits mitgeteilt habe, und ein paar Sachen, die mir noch aufgefallen sind.

2017-03-04 14:08 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        try {
Der Teil ab hier muss in die start Methode nach dem setupUI Aufruf.

2017-03-04 14:08 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                tank.setLiquid(new Liquid(value * tank.getCapacity(), tank.getLiquid().getTemperature(), tank.getLiquid().getColor()));
Hier und überall, wo die Füllstände gesetzt werden, reicht value direkt zu setzen, ohne die Capacity zu beachten.

2017-03-04 14:08 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        ErrorListener errorListener = new ErrorListener() {
Entweder hier oder an anderer Stelle muss noch eingefügt werden, dass bei Abbruch der Verbindung zu den Servern eine Meldung dem Nutzer angezeigt wird (Klasse Alert bietet sich an) und das Einstellungsfenster gezeigt wird. Außerdem, wenn die Überwachungskonsole beendet wird, müssen die OPC UA Clients beendet werden - egal, welche Fehler kommen. Im Moment ist es so: wenn zuerst die Simulation beendet wird und anschließend die Überwachungskonsole, können sich die Clients nicht abmelden und laufen theoretisch ewig weiter. Das darf nicht passieren.

2017-03-04 14:08 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        clientSubscribe(currentSettings.getFetchInterval(DEFAULT_FETCH_INTERVAL), currentSettings.getFetchInterval(DEFAULT_FETCH_INTERVAL));
Das Intervall für die Alarme sollte vielleicht noch etwas kleiner sein. Vor allem, wenn das eingestellte Intervall für die Werte auf 4 Sekunden liegt.

2017-03-04 16:24 UTC, Dav1dK requested changes
Die auskommentierten Sachen müssen halt noch gefixt/gelöscht werden

2017-03-04 16:24 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            cont.tank = currentProductionSite.getUpperTank(selector);
Kannst du currentProductionSite in prodSite oder productionSite umbenennen? Das current macht irgendwie keinen Sinn, weil es doch sowieso nur eine ProductionSite gibt.

2017-03-04 16:24 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        //throw new RuntimeException("Not implemented!");
Entweder sollte hier noch was hin, oder die Methode weg.

2017-03-04 16:24 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            System.err.println(e.getMessage());
Wie wärs wenn du ausgibst: System.err.println("Could not subscribe property: " + e.getMessage())? Damit kann der Benutzer vermutlich mehr anfangen.

2017-03-04 16:24 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Siehe oben^^

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +    private static final int DEFAULT_FETCH_INTERVAL = 100;
Würde das glaub ich langsamer machen. 500-1000 sollten reichen. Sonst spamt man gleich das komplette Netzwerk so voll.

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            alarmFetchInterval = 1;
Die Alarme würde ich eigentlich hard codieren auf 20-50ms oder so. Die Werte ändern sich nur selten (sind ja booleans), also wird es keine Netzwerklast auslösen. Nur ein bisschen mehr Arbeit für den Server. Finde, die Alarme sollten unabhängig vom fetch intervall immer fast instantan sein

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Da wäre noch sowas gut wie "Error while disconnectiong client. Continuing."

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    DEFAULT_HOSTNAME), currentSettings.getPort(mixCont.tank.getTankSelector(), defaultPort++)));
Würde die Zeile ein bisschen auseinander machen. Also kleine Variablen für Host und Port erstellen. Sonst ist das so ein riesen Assignment

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                        DEFAULT_HOSTNAME), currentSettings.getPort(cont.tank.getTankSelector(), defaultPort++)));
Würde ich auch kürzer machen

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    tank, currentSettingsViewInterface.isTemperatureOverheatingAlarmEnabled(tank));
Passt das in eine Zeile, wenn du `currentSettingsViewInterface` ein bisschen kürzer benennst?

2017-03-06 15:50 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +//        BooleanReceivedListener underflowSensorListener = new BooleanReceivedListener() {
Die Kommentare dann halt noch weg, sonst sieht es gut aus

2017-03-06 16:03 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                            + "from the server!");
Da fehlt ein Leerzeichen `disconnectedfrom the server`

2017-03-06 16:06 UTC, ByteHamster commented
```
Exception in thread "ua-shared-pool-3" java.lang.IllegalStateException: Not on FX application thread; currentThread = ua-shared-pool-3
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
	at javafx.scene.chart.LineChart.dataItemAdded(LineChart.java:291)
	at javafx.scene.chart.XYChart.dataItemsChanged(XYChart.java:501)
	at javafx.scene.chart.XYChart.access$2300(XYChart.java:93)
	at javafx.scene.chart.XYChart$Series$1.onChanged(XYChart.java:1488)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at edu.kit.pse.osip.monitoring.view.dashboard.ProgressVisualization.update(ProgressVisualization.java:113)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at edu.kit.pse.osip.core.model.base.AbstractTank.setLiquid(AbstractTank.java:57)
	at edu.kit.pse.osip.monitoring.controller.MonitoringController$Container$2.onReceived(MonitoringController.java:290)
	at edu.kit.pse.osip.core.opcua.client.UAClientWrapper.callReceivedListener(UAClientWrapper.java:397)
	at edu.kit.pse.osip.core.opcua.client.UAClientWrapper.lambda$null$3(UAClientWrapper.java:357)
	at org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaMonitoredItem.onValueArrived(OpcUaMonitoredItem.java:168)
	at org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscriptionManager.lambda$null$28(OpcUaSubscriptionManager.java:539)
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$PollAndExecute.run(ExecutionQueue.java:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

2017-03-06 19:46 UTC, HansMartinA commented
Für die Exception: Fix in #308.

2017-03-06 21:20 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Da wird doch dein Exception Text angezeigt, der das aussagt.

2017-03-06 21:36 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Die exception sagt das nicht ;) Hab intern eine Ausgabe, die `Continuing` enthält, aber das wird nicht geworfen.

2017-03-06 21:39 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    tank, currentSettingsViewInterface.isTemperatureOverheatingAlarmEnabled(tank));
Man müsste es schon um einige Zeichen kürzen und alle Abkürzungen, die mir einfallen, sind nicht so vielaussagend.

2017-03-06 21:41 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    tank, currentSettingsViewInterface.isTemperatureOverheatingAlarmEnabled(tank));
okay

2017-03-06 21:43 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Es geht dir ums continuing ?

2017-03-06 22:43 UTC, HansMartinA requested changes

2017-03-06 22:43 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +    private static final int DEFAULT_FETCH_INTERVAL = 1000;
Die Konstante existiert bereits in MonitoringViewConstants.

2017-03-07 10:52 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            System.err.println(e.getMessage());
Wenn ich so darüber nachdenke, solltest du das überall machen wo du die Exception Nachricht ausgibst. Denn aus der Nachricht selbst wird man nicht immer schlau.

2017-03-08 11:36 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            cont.tank = currentProductionSite.getUpperTank(selector);
Was ist jetzt damit?

2017-03-08 11:38 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Ich denke Exceptions sagen oft, was genau schief geht, aber nicht in welchem Kontext es passiert. Deswegen bin ich dafür die Ausgabe immer so zu machen: 
`System.err.println(Error while disconnecting: " + e.getMessage());`
(Das hab ich weiter oben ja auch schon mal bemängelt)

2017-03-08 11:41 UTC, Dav1dK requested changes

2017-03-08 11:41 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    default: System.err.println("An error occurred!");
Schreibe doch bitte dazu, bei was es einen Fehler gab. Also z.b. "Unknown OPC UA error" oder so

2017-03-08 11:41 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            System.err.println(e.getMessage());
Hier ebenfalls eine Beschreibung dazu, bei was die Exception auftrat.

2017-03-08 11:41 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Hier ebenfalls eine Beschreibung dazu, bei was die Exception auftrat.

2017-03-08 11:41 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    System.err.println(e.getMessage());
Hier ebenfalls eine Beschreibung dazu, bei was die Exception auftrat.

2017-03-08 11:47 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Ja, ich weiß. Aber bei manchen Meldungen sagt die Message schon, dass ein Fehler beim Disconnecten auftrat. Dann würde da stehen "Error while disconnecting:  Unable to disconnect from servers." Aber ok, ich machs noch dazu.

2017-03-08 12:00 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                System.err.println(e.getMessage());
Achso ok. In diesen Fällen ist es mir egal, das überlasse ich dir.

2017-03-08 15:05 UTC, Dav1dK commented
Ich bekomme eine Exception beim ändern der Temperatur. Zudem wird die Temperatur Skala nicht aktualisiert:
`Exception in thread "Thread-21" java.lang.ClassCastException: edu.kit.pse.osip.core.model.behavior.TemperatureAlarm cannot be cast to edu.kit.pse.osip.monitoring.view.dashboard.AlarmVisualization
        at edu.kit.pse.osip.monitoring.view.dashboard.Light.update(Light.java:91)
        at java.util.Observable.notifyObservers(Observable.java:159)
        at edu.kit.pse.osip.core.model.behavior.TankAlarm.update(TankAlarm.java:70)
        at java.util.Observable.notifyObservers(Observable.java:159)
        at edu.kit.pse.osip.core.model.base.AbstractTank.setLiquid(AbstractTank.java:57)
        at edu.kit.pse.osip.monitoring.controller.MonitoringController$Container$5.lambda$onReceived$0(MonitoringController.java:311)
        at edu.kit.pse.osip.core.opcua.client.UAClientWrapper.callReceivedListener(UAClientWrapper.java:397)
        at edu.kit.pse.osip.core.opcua.client.UAClientWrapper.lambda$doRead$2(UAClientWrapper.java:317)
        at java.lang.Thread.run(Thread.java:745)`

2017-03-08 15:11 UTC, Dav1dK commented
Die große Ampel wird nicht rot, obwohl der underflow Alarm des Mixtanks angegangen ist (der Kreis beim underflow Alarm wurde rot)

2017-03-08 15:24 UTC, marimbMax commented
Am zweiten Punkt arbeite ich gerade. Der erste Punkt sollte funktionieren, laut Logik. Ich weiß (noch) nicht warum es nicht geht.

2017-03-08 15:38 UTC, HansMartinA commented
Für die Exception und den ersten Punkt gibt es den Fix in #301.

2017-03-08 16:29 UTC, Dav1dK approved these changes

2017-03-09 11:09 UTC, HansMartinA approved these changes

2017-03-09 16:37 UTC, HansMartinA requested changes
- reSetupClients() beim Einstellungenspeichern in eigenem Thread ausführen, um Blockieren der GUI zu vermeiden.
- Einstellungsfenster, close-Button in Fensterleiste: Nichtstun bei deaktivierten Cancel-Button.
- close-Button des Hauptfensters: komplette Überwachungskonsole beenden (kein System.exit(), sondern zur Ausführung der stop Methode kommen).

2017-03-10 20:08 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Das finde ich ehrlich gesagt nicht so super. X sollte eher die Einstellungen verwerfen.

2017-03-10 20:11 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Aber wir wollen nicht das man hier die Einstellungen verwerfen kann. Es geht ja darum, den Benutzer zu zwingen korrekte Port Einstellungen zu tätigen bevor er die Einstellungen schließen kann.

2017-03-10 20:15 UTC, marimbMax commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Das müsst ihr unter euch ausmachen.

2017-03-10 20:16 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Wenn du also das Programm einmal gestartet hast, bekommst du es nicht mehr geschlossen? Nur über das Starten der Simulation und setzen der Variablen? Also meiner Meinung nach sollte man nur im äußersten Notfall die standard-Aktionen eines Fensters bearbeiten. Dann lieber das ganze gleich schließen. Aber schon gar nicht ohne jegliche Rückmeldung an den User einfach den wichtigsten aller Knöpfe ignorieren

2017-03-10 20:25 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Für das Beenden der Überwachungskonsole ist der x Button des Hauptfensters da. Ich schließe mich hier David an: entweder der Nutzer gibt korrekte Daten ein oder er kann das Einstellungsfenster nicht schließen, oder (als letzte Möglichkeit) das x des Einstellungsfensters schließt in einem solchen Fall ebenfalls die komplette Überwachungskonsole. Beides widerspricht den üblichen Erwartungen. Aber ansonsten kann der Nutzer das Einstellungsfenster einfach schließen und dann? Dann kann er mit der Überwachungskonsole nichts anfangen.

2017-03-10 20:27 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Genau, es geht hier ja nur um das X des Einstellungsfensters. Wenn der Benutzer das einfach schließen könnte, hätte er ein Hauptfenster das keine Daten anzeigt.

2017-03-10 20:33 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Dann bitte ein Popup: "Sie haben keine gültigen Daten eingegeben. Wenn Sie jetzt die Einstellungen schließen, wird das Programm beendet."

Und darauf achten, dass das nur ganz am Anfang kommt. Wenn man im laufenden Betrieb die Einstellungen weg macht, wird einfach nicht gespeichert.

2017-03-10 20:55 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Da würde ich eher eine Meldung über den Textfeldern anzeigen, kein neues Fenster öffnen.
Und ich würde den Knopf trotzdem deaktivieren. Das Programm kann man ja nach wie vor wie gewohnt schließen. Ich fände es nämlich sehr überraschend wenn sich das Programm beendet weil ich den cancel Knopf drücke.

2017-03-10 21:10 UTC, marimbMax commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Über welchen Textfeldern ?

2017-03-10 21:26 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Und ein kurzes Popup mit der Meldung, man soll es beheben? Ohne Schließen? Schrift innerhalb des Dialogs ist nicht genug, um sowas wie ein ignoriertes Schließen event zu rechtfertigen

2017-03-11 04:56 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/settings/SettingsMainWindow.java
> +        });
Hmm ja das wäre in Ordnung. Also wenn man auf das X drückt kommt ein Popup der einen darauf hinweist, dass man die Einstellungen richtig setzen soll. Den Cancel Button würde ich trotzdem deaktivieren, oder?

2017-03-11 09:52 UTC, ByteHamster commented
AbstractTankClient.releaseSharedResources();

Ganz am Ende in der end() Methode. Musst erst rebasen

2017-03-11 10:46 UTC, ByteHamster requested changes
Gesperrte Settings

2017-03-11 10:48 UTC, ByteHamster commented
Die gesperrten Settings sind irgendwie sinnlos, wenn man ungültige Sachen eintragen kann und dann mit "Save" trotzdem das Programm benutzen kann.

Die Fenster von Fehlermeldung und Settings sollten im Vordergrund aufgehen. Habe mich gerade einige Sekunden gewundert, warum sich die UI nicht benutzen lässt

2017-03-11 12:42 UTC, ByteHamster requested changes

2017-03-11 12:42 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +    private void handleSaveButton(ClientSettingsWrapper settings,
Die Funktion wird auch beim Start aufgerufen. Dann darf sie nicht mehr `handleSaveButton` heißen.

2017-03-11 12:42 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            cont.client.releaseSharedResources();
Das release darf insgesamt nur 1x aufgerufen werden. Ganz am Ende über die abstrakte Klasse am besten

2017-03-11 12:42 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        reSetup.start();
Bei ungünstigem Scheduling (bei mir etwa 8/10 Starts) kann es nicht verbinden. Bitte das wieder raus. Sonst wird teilweise clientSubscribe aufgerufen, bevor reSetup fertig ist

2017-03-11 12:43 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            cont.client.releaseSharedResources();
Wenn nicht, dann können alle anderen Clients nicht richtig disconnected werden

2017-03-11 12:45 UTC, ByteHamster commented
Clients nur neu starten, wenn sich der Port geändert hat

2017-03-11 13:37 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                            currentSettingsView.showDisconnectAlert();
Der funktioniert glaube ich nicht, wenn das settings fenster gerade nicht offen ist

2017-03-11 18:31 UTC, ByteHamster requested changes

2017-03-11 18:31 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +            currentMonitoringViewInterface.setOverflowAlarmEnabled(
Bitte aufteilen in 2 Methoden. Einmal nur `currentSettings.set` und einmal `currentMonitoringViewInterface.set`. Dann nur die mit `currentMonitoringViewInterface.set` im Konstruktor

2017-03-12 11:29 UTC, HansMartinA requested changes

2017-03-12 11:29 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        boolean portChanged = true;
Das mit portChanged funktioniert so nicht. Hat sich nur ein Port nicht geändert, werden die Clients nicht neugestartet und damit werden von den Clients mit geänderten Ports keine Werte mehr empfangen.

2017-03-12 11:45 UTC, ByteHamster requested changes

2017-03-12 11:45 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    oldMix.disconnectClient();
Wenn 2 Tanks die Ports tauschen, funktioniert das nicht. Bitte erst alle beenden, die sich geändert haben

2017-03-12 11:46 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +        boolean portChanged = true;
Stimmt. Da habe ich nicht aufgepasst.

2017-03-12 11:47 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                    oldMix.disconnectClient();
Okay einfacher: Wenn sich einer geändert hat, dann alle beenden und neu starten. So macht es die Simulation auch

2017-03-12 18:14 UTC, Dav1dK requested changes
Der disconnect Alert Dialog wird momentan vier mal (für jeden Client) erstellt. Es wäre natürlich schöner wenn das nur einmal passiert. Also speichere den Dialog ab und benutze .show()

2017-03-12 18:42 UTC, Dav1dK approved these changes

2017-03-12 18:49 UTC, HansMartinA requested changes

2017-03-12 18:49 UTC, HansMartinA commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> +                ALARM_FETCH_INTERVAL);
Die sync Methode muss wieder rein und hier aufgerufen werdne.

2017-03-12 19:19 UTC, ByteHamster approved these changes

2017-03-12 20:06 UTC, HansMartinA approved these changes

2017-03-12 20:08 UTC, merged