Corrections
ByteHamster/PSE pull request #308
Opened 2017-03-03 23:00 UTC by HansMartinA

Diverse Änderungen:
- Verbesserungen in den Monitoring-Settings.
- Tanknamen.
- Fenstergröße für nicht maximiertes Fenster.
- Konstanten angepasst, u. a. für Alarme und Schriftgröße.
- Settingsfile in der Simulation korrigiert.

2017-03-04 08:56 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/MonitoringMainWindow.java
> +        primaryStage.setMinWidth(WIDTH);
Warum braucht man hier ein Minimum? Die minimum Höhe passt fast nicht auf meinen Laptop. Würde nur die Werte setzen, aber nicht min

2017-03-04 08:56 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/resources/Bundle.properties
> +monitoring.tank.tankName=%s Tank
Scheibt man das Tank dann nicht klein?

2017-03-04 13:58 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/resources/Bundle.properties
> +monitoring.tank.tankName=%s Tank
Es ist der Tank. Außerdem dachte ich, schadet es an dieser Stelle nichts, da es der Tankname ist.

2017-03-04 14:36 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/resources/Bundle.properties
> +monitoring.tank.tankName=%s Tank
Jaaa auf deutsch schreibt man es groß ;) Ist aber doch Englisch ;)

2017-03-06 07:58 UTC, Dav1dK requested changes

2017-03-06 07:58 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/MonitoringViewConstants.java
> +    public static final Float TEMPERATURE_UNDERCOOLING_THRESHOLD = Float.valueOf(SimulationConstants.MIN_TEMPERATURE
Also ich habe in der Simulation feste Werte genommen, die m.M.n. mehr Sinn ergeben: Als Untergrenze 0°C (damit kein Wasser gefriert) und als Obergrenze 100°C (damit nichts kocht). Diese Werte gelten natürlich nur für Wasser, aber bei den Flüssigkeiten denkt man vielleicht auch erst mal an Wasser.

2017-03-06 21:38 UTC, ByteHamster commented
Kannst du die Charts auch so machen, dass keine Punkte angezeigt werden, sondern nur Linien? Momentan macht der ja bei jedem empfangenen Wert einen Punkt. Bei vielen Werten sieht das dann aus wie eine riesige Linie.

2017-03-07 10:50 UTC, Dav1dK approved these changes

2017-03-07 15:15 UTC, ByteHamster approved these changes

2017-03-07 19:52 UTC, merged