[doc] Added structure of implementation document
ByteHamster/PSE pull request #311
Opened 2017-03-04 14:35 UTC by ByteHamster

2017-03-04 16:29 UTC, Dav1dK requested changes
Sonst siehts gut aus.

2017-03-04 16:29 UTC, Dav1dK commented on docs/Implementation.tex
> +
\thispagestyle{empty}

2017-03-04 18:27 UTC, HansMartinA submitted a review, later dismissed

2017-03-04 18:27 UTC, HansMartinA commented on docs/Implementation.tex
> +\section{Implementierte Muss- und Wunschkriterien}
Ich hätte hier Kannkriterien geschrieben, da wir das schon so im Pflichtenheft und im Entwurf hatten.

2017-03-05 16:58 UTC, Dav1dK approved these changes

2017-03-06 15:51 UTC, merged