Simulation view rotating fix
ByteHamster/PSE pull request #315
Opened 2017-03-05 00:27 UTC by NikoWil

Es gibt keine Spruenge mehr in der Animation, wenn sich die Geschwindigkeit drehender Elemente aendert.
Die Kreise in ValveDrawer drehen sich nur noch, wenn aktuell immer noch Liquid einer Menge > 0 in die Pipe eingegeben wird.
Dazu wurde die Simulation geaendert, damit tatsaechlich Liquid in die Pipe gegeben wird, die den MixTank verlaesst, da sich der ValveDrawer sonst nicht drehen wuerde.

2017-03-05 17:18 UTC, Dav1dK requested changes

2017-03-05 17:18 UTC, Dav1dK commented on src/osip-model/src/main/java/edu/kit/pse/osip/core/model/base/Pipe.java
> +    public boolean liquidIsEntering() {
Ich würde diese Methode in `isLiquidEntering()` umbenennen, das passt mehr zu den üblichen Bennenungsschemata.

2017-03-05 17:18 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/Drawer.java
> +     * @param timeDiff The difference in time in minutes since the last call of draw.
Sollte da wirklich `in minutes` stehen? Klingt ein bisschen viel...

2017-03-05 17:26 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/Drawer.java
> +     * @param timeDiff The difference in time in minutes since the last call of draw.
Ja.
Der Parameter wird im ApplicationTimer berechnet. Dabei wird der aktuell uebergebene Wert in Ns (den der ApplicationTimer bekomme) minus dem letzten Wert gerechnet. Dann / (1000000000 * 60) (Anzahl Ns pro Minute).
In Minuten wird es umgerechnet, um dann Drehzahlen die ja alle in U/ min gegeben sind leichter darstellen zu koennen und das nicht in jeder Klasse separat machen zu muessen.

2017-03-05 18:52 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/Drawer.java
> +     * @param timeDiff The difference in time in minutes since the last call of draw.
Achso ok stimmt. Aber müsste der Paramter `time` in den Unterklassen nicht noch in `timeDiff` umbenannt werden?

2017-03-06 15:56 UTC, ByteHamster approved these changes

2017-03-06 21:08 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/Drawer.java
> +     * @param timeDiff The difference in time in minutes since the last call of draw.
Korrekt.

2017-03-06 21:17 UTC, NikoWil commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/Drawer.java
> +     * @param timeDiff The difference in time in minutes since the last call of draw.
Ich hab jetzt auch direkt noch Kommentare bei den draw() Methoden entfernt, die reines Duplikat des Kommentars im Interface waren.

2017-03-07 10:49 UTC, Dav1dK approved these changes

2017-03-07 14:27 UTC, merged