[simulation/controller] Don't restart server if port didn't change
ByteHamster/PSE pull request #326
Opened 2017-03-09 12:49 UTC by Dav1dK

Otherwise the restart will fail, because the old server gets stopped
after starting the new server.

2017-03-09 14:14 UTC, ByteHamster requested changes
Das funktioniert aber glaub immer noch nicht, wenn zwei Server einfach die Ports tauschen. Ich finde, es sollte zuerst beendet werden, bevor ein neuer Server gestartet wird

2017-03-09 21:21 UTC, Dav1dK commented
Ich glaube am besten wäre es, zu überprüfen ob ein Port doppelt genommen wird, dann alle Server beenden und anschließend alle Server zu starten, oder?

2017-03-09 21:23 UTC, ByteHamster commented
Wenn man invalide Ports einstellt, sollte meiner Meinung nach einfach der entsprechende Server nicht laufen. Anstatt zu laufen, aber auf einem falschen (alten) Port

2017-03-09 21:24 UTC, Dav1dK commented
Ja das macht Sinn. Aber was meinst du mit invalide? Falscher Wertebereich oder doppelt belegte Ports?

2017-03-09 21:25 UTC, ByteHamster commented
Doppelt belegt oder im System schon anderweitig genutzt

2017-03-09 21:34 UTC, Dav1dK commented
Wenn man doppelte Ports einstellt, dann sollte kein Server laufen finde ich. Bei Doppelbelegungen reicht es, wenn der betroffene Server nicht läuft.

2017-03-09 21:45 UTC, ByteHamster commented
Okay, das bedeutet aber ja dann immernoch, dass man einfach alle beenden kann und dann erst neu starten. Dann muss man sich nichts fürs Tauschen überlegen. Momentan beendest du ja glaube ich nur, wenn der neue erfolgreich gestartet wurde

2017-03-09 21:57 UTC, Dav1dK commented
Ja genau, hab ich ja oben geschrieben

> Ich glaube am besten wäre es, zu überprüfen ob ein Port doppelt genommen wird, dann alle Server beenden und anschließend alle Server zu starten, oder?

2017-03-09 22:06 UTC, ByteHamster commented
Die doppelte Benutzung kann man doch auch direkt in der Schleife machen, die die Server startet. Dann wird halt einfach immer der erste gestartet

2017-03-10 17:41 UTC, Dav1dK commented
Aber ich finde dann sollte es einen Fehler geben. Ich füge vielleicht noch so ein Fehlerfenster hinzu.

2017-03-11 09:58 UTC, ByteHamster approved these changes

2017-03-11 10:07 UTC, merged