[doc] Added rejected 3D server UI to appendix
ByteHamster/PSE pull request #34
Opened 2016-12-06 07:49 UTC by ByteHamster

2016-12-06 19:20 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +Die 3D-Darstellung des Servers wurde verworfen, da dieser sonst sehr verspielt wirkt.
Ich finde, die Verwendung von "verspielt" passt nicht ins Pflichtenheft. Ich würde eher etwas wie "zu kunstvoll" o. ä. nehmen.

2016-12-06 19:29 UTC, Dav1dK requested changes

2016-12-06 19:29 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +Die 3D-Darstellung des Servers wurde verworfen, da dieser sonst sehr verspielt wirkt.
Haben wir uns nicht auf Fertigungssimulation anstatt Server geeinigt?

2016-12-06 20:10 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Die 3D-Darstellung des Servers wurde verworfen, da dieser sonst sehr verspielt wirkt.
Stimmt

2016-12-06 20:13 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +Die 3D-Darstellung des Servers wurde verworfen, da dieser sonst sehr verspielt wirkt.
Ich finde "verspielt" eigentlich ziemlich passend. Als ich das gerendert hatte, hab ich als allererstes an ein Spiel gedacht (David ja auch). Kunstvoll ist ja eigentlich was anderes. Wärst du einverstanden mit "... es eher wie ein Spiel wirkt"?

2016-12-06 20:20 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +Die 3D-Darstellung des Servers wurde verworfen, da dieser sonst sehr verspielt wirkt.
Ja, das passt besser.

2016-12-07 12:59 UTC, Dav1dK approved these changes

2016-12-07 12:59 UTC, merged