[doc] Specifications goal
ByteHamster/PSE pull request #36
Opened 2016-12-06 18:03 UTC by NikoWil

Ein paar Ideen fuer Muss-/ Kann-/ Abgrenzungskriterien.

2016-12-06 18:42 UTC, HansMartinA requested changes

2016-12-06 18:42 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +  \item In der \gls{Uberwachungskonsole} kann der Benutzer beliebig eigene Alarme einstellen.
Ich hätte feste Alarme vorgegeben und die ein- und ausschaltbar gemacht (als Kannkriterium). Oder meinst du an dieser Stelle, dass der Nutzer die vorhandenen Alarme einstellen kann?

2016-12-06 19:30 UTC, Dav1dK requested changes

2016-12-06 19:30 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    Implementierung Milo des \gls{OPC UA} Protokolls verwendet. \gls{OPC UA} wird nicht selbst implementiert.
Wie wärs wenn wir Milo irgendwie verlinken, z.b. mit einer Fußnote?

2016-12-07 09:38 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +  \item In der \gls{Uberwachungskonsole} kann der Benutzer beliebig eigene Alarme einstellen.
Ich dachte Alarme vorgegeben im Sinne von man kann nach Fuellstand und Temperatur pruefen. Gerade die Grenzen (z.B. bei welchem Fuellstand ausgeloest wird) aber frei festlegbar zu machen.

2016-12-07 09:38 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +    Implementierung Milo des \gls{OPC UA} Protokolls verwendet. \gls{OPC UA} wird nicht selbst implementiert.
Wo passt das am besten? Im Glossar?

2016-12-07 13:00 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    Implementierung Milo des \gls{OPC UA} Protokolls verwendet. \gls{OPC UA} wird nicht selbst implementiert.
Ja ich denke schon.

2016-12-07 13:38 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +    Implementierung Milo des \gls{OPC UA} Protokolls verwendet. \gls{OPC UA} wird nicht selbst implementiert.
Ist jetzt drin.

2016-12-07 19:03 UTC, ByteHamster requested changes
Hier wird noch von Makros geredet. Bitte raus machen.

2016-12-07 19:09 UTC, HansMartinA approved these changes

2016-12-07 19:37 UTC, Dav1dK approved these changes

2016-12-07 20:53 UTC, ByteHamster approved these changes

2016-12-07 20:55 UTC, merged