[doc] Added workflow
ByteHamster/PSE pull request #370
Opened 2017-03-11 17:11 UTC by ByteHamster

2017-03-11 17:23 UTC, Dav1dK requested changes

2017-03-11 17:23 UTC, Dav1dK commented on docs/Implementation.tex
> +durch den Dienst "`Travis"' bei jeder einzubindenden Änderung die Stil-Richtlinien und die Unit Tests überprüfen. Dieses Vorgehen erforderte
Vielleicht noch hinzufügen, dass wir dafür Checkstyle verwendet haben?

2017-03-11 17:23 UTC, Dav1dK commented on docs/Implementation.tex
> +Um die Aufgaben der einzelnen Kommilitonen aufeinander abzustimmen, setzten wir die von GitHub bereitgestellten Issues ein. Im Laufe der
setzten wir den von GitHub bereitgestellten **Issue-Tracker** ein?

2017-03-11 17:23 UTC, Dav1dK commented on docs/Implementation.tex
> +Entwicklung von OSIP wurden über 400 Issues und Pull requests erstellt.
Die Groß-/Kleinschreibung von Pull requests sieht falsch aus. Entweder **Pullrequest** oder **Pull Request**.

2017-03-11 17:26 UTC, ByteHamster commented on docs/Implementation.tex
> +Entwicklung von OSIP wurden über 400 Issues und Pull requests erstellt.
Scroll mal hoch zum Tab auf GitHub ;) Wollte es auch zuerst groß schreiben

2017-03-12 10:04 UTC, Dav1dK requested changes

2017-03-12 10:04 UTC, Dav1dK commented on docs/Implementation.tex
> +\section{Arbeitsaufteilung}
Haben wir nicht eher Outside-In gemacht, weil wir gleichzeitig mit View und Model angefangen haben? Au0erdem würde ich dazu schreiben, warum wir das so gemacht haben (also weil sich Niko und Martin mit der aufwändigen View auskannten, und wir anderen so lange das Model machen konnten, bis der Großteil des Views implementiert war)

2017-03-12 10:04 UTC, Dav1dK commented on docs/Implementation.tex
> +Um die Funktionalität von OPC UA Server und Client zu testen, musste von reinen unit tests abgewichen werden, da der Client keine
Ich bin mit der Rechtschreibung von **unit test** und **Unit test** nicht einverstanden. Klar, es ist ein englisches Wort, aber es sieht in einem deutschen Text falsch aus. Ich schlage **Unittest** vor.

2017-03-12 10:04 UTC, Dav1dK commented on docs/Implementation.tex
> +In UI und Controller wurden keine automatischen Unit tests eingesetzt, sondern die Funktionalität bei Pull requests manuell getestet.
Wie wäre es, das noch zu begründen? Das testen würde (insbesondere bei der View) einen hohen Aufwand bedeuten, der sich kaum Lohnt weil es kaum komplexe, gut testbare Codeabschnitte gibt?

2017-03-12 11:10 UTC, Dav1dK approved these changes

2017-03-12 11:19 UTC, merged