Unit tests max
ByteHamster/PSE pull request #438
Opened 2017-03-19 14:41 UTC by marimbMax

2017-03-20 08:14 UTC, ByteHamster commented
Du hast wieder eine PDF Datei mit commited

2017-03-20 09:37 UTC, Dav1dK requested changes

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        outStreamNullEntry.print("fetchIntervall=80");
Verwende println("fetchIntervall=80"); und spare dir dann immer das println() darunter

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        outStreamInvalidEntry.print("fetchInterval=8G0AER");
Hier ebenfalls direkt println verwenden und TankSelector.valuesWithoutMix()[0] in einer Variable speichern.

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        outStreamNullEntry.print("overflowAlarmm_" + (TankSelector.valuesWithoutMix()[0]) + "=" + "false");
Ich glaube es wäre besser lesbar wenn du TankSelector.valuesWithoutMix()[0] vor den ganzen print Aufrufen in eine Variable speicherst

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        assertEquals(interval, 1122);
Vertausche die Argumente von assertEquals überall. Es kommt immer zuerst das erwartete Ergebnis und dann das tatsächliche Ergebnis.

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        assertEquals(value, false);
assertFalse(value). Verwende weiter unten bitte auch immer assertFalse oder assertTrue wenn du booleans testest.

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        assertEquals(value, false);
Kannst du das auch noch mit Defaultwert true testen?

2017-03-20 09:37 UTC, Dav1dK commented on src/osip-model/src/test/java/edu/kit/pse/osip/core/model/behavior/TankAlarmObservableTest.java
> +        assertEquals(false, tObserver.wasNotified());
assertFalse

2017-03-21 09:59 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        boolean value = wrapperInvalidEntry.getTempDiagram(TankSelector.valuesWithoutMix()[0], false);
Bitte alle `TankSelector.valuesWithoutMix()[0]` in dieser Datei mit `testTank` ersetzen

2017-03-21 09:59 UTC, Dav1dK commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        assertEquals(interval, 1122);
Machst du das noch? Es ist nicht unbedingt nötig, aber die Ausgabe wenn ein Test fehlschlägt ist sonst falsch.

2017-03-21 20:24 UTC, marimbMax commented on src/osip-core/src/test/java/edu/kit/pse/osip/core/io/files/ClientSettingsWrapperTest.java
> +        assertEquals(interval, 1122);
Ja, mache ich noch. Ich war gestern zu müde dafür.

2017-03-22 12:38 UTC, Dav1dK approved these changes

2017-03-22 13:26 UTC, merged