[monitoring/controller] Consistent handling of servers
ByteHamster/PSE pull request #458
Opened 2017-03-29 17:16 UTC by ByteHamster

2017-03-29 18:36 UTC, Dav1dK requested changes

2017-03-29 18:36 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                        if (errorListenerEnabled) {
Hat es keine Auswirkungen, dass diese Abfrage fehlt?

2017-03-29 18:36 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                setupClients();
Wird setupClients jetzt überhaupt noch benötigt?

2017-03-29 19:44 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                setupClients();
Nein, hab die Methode auch gelöscht

2017-03-29 19:45 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                        if (errorListenerEnabled) {
Mir ist zumindest keine aufgefallen... Das wurde glaub hauptsächlich verwendet, um die error messages während dem Disconnect abzufangen. Vielleicht sollte aber @marimbMax nochmal drüber schauen.

2017-03-29 19:51 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                setupClients();
Ohh stimmt, das hab ich übersehen.

2017-03-29 19:51 UTC, Dav1dK commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                        if (errorListenerEnabled) {
Ok, dann approve ich das mal, aber warte noch auf @marimbMax

2017-03-29 19:52 UTC, Dav1dK approved these changes

2017-03-29 21:47 UTC, marimbMax commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                        if (errorListenerEnabled) {
HaPe hat Recht. Das war um den Disconnect Dialog beim gewollten Disconnect auszuschalten. Aber wie wird es jetzt gesteuert ? Wird nicht immer der Disconnect Dialog + SettingsFenster angezeigt wenn die reSetup aufgerufen wird ?

2017-03-29 23:30 UTC, ByteHamster commented on src/osip-monitoring-controller/src/main/java/edu/kit/pse/osip/monitoring/controller/MonitoringController.java
> -                        if (errorListenerEnabled) {
Wenn man disconnect() macht, wird der error listener mittlerweile vom UAClientWrapper automatisch vorher deaktiviert

2017-03-30 08:46 UTC, marimbMax approved these changes

2017-03-30 09:47 UTC, merged