[monitor/view] Disable progression tabs and clear data when disabled
ByteHamster/PSE pull request #460
Opened 2017-03-29 19:11 UTC by Dav1dK

Otherwise the progressions just stop, but it isn't visible that they are
disabled.

2017-03-29 19:55 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressVisualization.java
> +            progressSeries.getData().clear();
Hier könntest du noch `x = 0;` machen, damit der Zähler auf der x-Achse wieder bei 0 beginnt

2017-03-29 20:01 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressVisualization.java
> +            progressSeries.getData().clear();
Stimmt, habs hinzugefügt.

2017-03-29 20:02 UTC, HansMartinA requested changes

2017-03-29 20:02 UTC, HansMartinA commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressOverview.java
> +        tabFillLevel.setDisable(!progressEnabled);
Ich würde hier die Tabs nicht ausschalten. Die Charts finde ich in Ordnung, aber es ist komisch, wenn ich einen deaktivierten Tab habe, auf einen anderen schalten und nicht wieder zurückschalten kann.

2017-03-29 20:13 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressOverview.java
> +        tabFillLevel.setDisable(!progressEnabled);
Die sind glaub tatsächlich beide deaktiviert

2017-03-29 20:16 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressOverview.java
> +        tabFillLevel.setDisable(!progressEnabled);
Die sind aber gar nicht deaktiviert, wenn man ganz am Anfang keine Verbindung bekommt

2017-03-30 05:56 UTC, Dav1dK commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressOverview.java
> +        tabFillLevel.setDisable(!progressEnabled);
Also ich finde es in Ordnung die Tabs zu deaktivieren. Das deaktivieren der Charts finde ich nicht sichtbar genug. Was meinen die anderen dazu?

@ByteHamster Was meinst du damit? Wenn ich den Monitor ohne Simulation starte, dann sind die Tabs und Diagramme bei mir deaktiviert.

2017-03-30 09:16 UTC, ByteHamster commented on src/osip-monitoring-view/src/main/java/edu/kit/pse/osip/monitoring/view/dashboard/ProgressOverview.java
> +        tabFillLevel.setDisable(!progressEnabled);
Hab wohl zu schnell kompiliert. Alles OK

2017-03-30 12:58 UTC, ByteHamster approved these changes

2017-03-30 18:41 UTC, HansMartinA approved these changes

2017-03-30 18:41 UTC, merged