[view] Changed alert dialogs to modal windows
ByteHamster/PSE pull request #476
Opened 2017-03-31 11:28 UTC by ByteHamster

This way, the underlaying window can not be selected without showing the
alert dialog. This helps to prevent the situation where you can not interact
with a window because the alert dialog is shown in background.

2017-03-31 11:29 UTC, ByteHamster commented
Es fehlt noch der alarm dialog, aber da kommt man nicht an die Stage ran, die man als Owner setzt. @HansMartinA Hast du eine Idee?

2017-03-31 14:32 UTC, Dav1dK requested changes

2017-03-31 14:32 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +            errorDialog.initOwner(stage);
Ich überschreibe Stage zwei Zeilen drüber. Das mag keine gute Entscheidung sein, aber diese Zeilen müssen zwei Zeilen weiter hoch, sonst kommt eine Exception weil der Owner nicht die Stage selbst sein kann. Allerdings wäre es sinnvoller wenn der Owner des Dialogs das SettingsWindow wäre, denn wenn dieser Fehler kommt, interagiert man mit den Einstellungen.

2017-03-31 14:32 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +            errorDialog.initOwner(stage);
Dazu müsste man den Dialog vermutlich über die Einstellungen öffnen.

2017-03-31 14:49 UTC, ByteHamster commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +            errorDialog.initOwner(stage);
Stimmt gut aufgepasst. Das Parent auf den settings dialog zu setzen ist glaub jetzt nicht mehr sinnvoll machbar.

2017-03-31 14:50 UTC, Dav1dK commented on src/osip-simulation-view/src/main/java/edu/kit/pse/osip/simulation/view/main/SimulationMainWindow.java
> +            errorDialog.initOwner(stage);
Ja das vermute ich leider auch.

2017-04-01 10:08 UTC, Dav1dK approved these changes

2017-04-01 16:08 UTC, merged