[doc] Add implementation changes to testdocument
ByteHamster/PSE pull request #492
Opened 2017-04-05 14:41 UTC by Dav1dK

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> +Während der Testphase wurde einige Fehler behoben und Verhaltensweisen verändert um OSIP benutzerfreundlicher zu machen.
Vor um ein Komma

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> + \item Vereinfachen von Übersetzungen von OSIP in andere Sprachen, in dem die lokalisierten Fehlermeldungen sämtlicher Exceptions benutzt werden.
In dem oder indem

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> + \item Beheben von Verklemmungen durch zu starke Synchronisierung zwischen Threads.
Das war nur einen Commit lang ein Problem

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> + \item Öffnen sämtlicher Dialoge (wie z.B. Alarmmeldungen, Einstellungen oder Überlaufmeldungen) über den anderen Fenstern und model machen dieser Dialoge,
Model?

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> + so dass OSIP nicht bedienbar ist solange diese nicht geschlossen werden. Das verhindert beispielsweise, dass der Benutzer nach einem Verbindungsverlust
So dass oder sodass

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> + die Einstellungen nicht bedienen kann weil der Fehlerdialog im Hintergrund unbemerkt offen ist.
Komma vor weil

2017-04-05 14:53 UTC, ByteHamster commented on docs/Qualitaetssicherung.tex
> + Einstellungsfenster geöffnet. Außerdem wurde sichergestellt, dass der Benutzer die Einstellungen in jedem Zustand aufrufen kann.
Das in jedem Zustand war so eine Art Regression durch die Thread separierung. Die fand aber auch in der aktuellen Phase statt (als bug fix für langsames UI)

2017-04-05 15:10 UTC, Dav1dK commented on docs/Qualitaetssicherung.tex
> + \item Öffnen sämtlicher Dialoge (wie z.B. Alarmmeldungen, Einstellungen oder Überlaufmeldungen) über den anderen Fenstern und model machen dieser Dialoge,
Ups. Ich meinte modal

2017-04-05 15:11 UTC, Dav1dK commented on docs/Qualitaetssicherung.tex
> + Einstellungsfenster geöffnet. Außerdem wurde sichergestellt, dass der Benutzer die Einstellungen in jedem Zustand aufrufen kann.
Achso ok.

2017-04-05 15:11 UTC, Dav1dK commented on docs/Qualitaetssicherung.tex
> + \item Beheben von Verklemmungen durch zu starke Synchronisierung zwischen Threads.
Achso ok.

2017-04-05 15:40 UTC, HansMartinA requested changes

2017-04-05 15:40 UTC, HansMartinA commented on docs/Qualitaetssicherung.tex
> + \item Besseres visualisieren von ausgeschalteten Verläufen.
Großes V für "Visualisieren".

2017-04-05 15:40 UTC, HansMartinA commented on docs/Qualitaetssicherung.tex
> + sodass OSIP nicht bedienbar ist solange diese nicht geschlossen werden. Das verhindert beispielsweise, dass der Benutzer nach einem Verbindungsverlust
Vor "solange" kommt ein Komma.

2017-04-05 15:40 UTC, HansMartinA commented on docs/Qualitaetssicherung.tex
> + \item Öffnen sämtlicher Dialoge (wie z.B. Alarmmeldungen, Einstellungen oder Überlaufmeldungen) über den anderen Fenstern und modal machen dieser Dialoge,
und modale Initialisierung dieser Dialoge,
Das klingt besser, finde ich.

2017-04-05 15:40 UTC, HansMartinA commented on docs/Qualitaetssicherung.tex
> +Diese Probleme wurde nicht notwendigerweise durch die Testszenarien aufgedeckt, da die Verhaltensweisen nicht so genau
wurde [hier fehlt ein n] nicht [...] , da die Verhaltensweisen nicht [im Fokus des Pflichtenhefts und daher nicht ] genau spezifiziert [waren] oder die Szenarien [durch ihre Beschränkung auf Abdeckung aller Anforderungen] nicht aufdecken konnten.
Ich hätte die Erläuterung noch etwas präziser gemacht, da es für mich so klingt wie "Wir haben uns keine Mühe beim Pflichtenheft gegeben und mussten jetzt nochmal alles anpassen." (vielleicht etwas übertrieben, aber in diese Richtung geht es).

2017-04-06 04:16 UTC, Dav1dK commented on docs/Qualitaetssicherung.tex
> + \item Öffnen sämtlicher Dialoge (wie z.B. Alarmmeldungen, Einstellungen oder Überlaufmeldungen) über den anderen Fenstern und modal machen dieser Dialoge,
Danke, das "modal machen" fand ich auch die ganze Zeit komisch, aber mir ist nichts besseres eingefallen :D

2017-04-06 04:21 UTC, Dav1dK commented on docs/Qualitaetssicherung.tex
> +Diese Probleme wurde nicht notwendigerweise durch die Testszenarien aufgedeckt, da die Verhaltensweisen nicht so genau
Besser so?

2017-04-06 21:25 UTC, HansMartinA requested changes
Danach bin ich zufrieden :)

2017-04-06 21:25 UTC, HansMartinA commented on docs/Qualitaetssicherung.tex
> +Pflichtenhefts standen und daher nicht so genau spezifiziert sind (u.a. da Fragen zu Details der GUI oder zum Verhalten beim Netzwerkproblemen
spezifiziert [waren] [...] oder zum Verhalten bei [ohne m] [...] nicht audecken konnten [Komma] weil sie nur durch [ohne eine] bestimmte [...]

2017-04-08 16:23 UTC, HansMartinA approved these changes

2017-04-10 11:21 UTC, merged