[parser] Removing UTF-8 BOM
ByteHamster/PSE pull request #497
Opened 2017-04-20 11:26 UTC by ByteHamster

2017-04-21 22:04 UTC, HansMartinA requested changes
Aus der IDE heraus ausgeführt, funktioniert es, aber als JAR nicht. Ursache hierfür ist der Konstruktor in edu.kit.pse.osip.core.io.files.ScenarioFile. Dieser erstellt ja einen String mit dem Dateiinhalt und verwendet dabei das Standardencoding, welches bei mir durch Eclipse bei UTF-8 ist, aber als JAR unter Windows nicht. Daher muss im String-Konstruktor als zweites Argument "UTF-8" mit übergeben werden, also
new String(Files.readAllBytes(Paths.get(file)), "UTF-8")
, womit das Encoding stimmt und die Datei richtig geparst werden kann.

2017-04-21 22:04 UTC, HansMartinA commented on src/osip-core/src/main/java/edu/kit/pse/osip/core/io/files/ScenarioParser.java
> +     * Skips the UTF-8 ByteOrderMark that is sometimes added to the beginning of a file.
Hiernach bitte eine Leerzeile.

2017-04-22 10:29 UTC, ByteHamster commented
> new String(Files.readAllBytes(Paths.get(file)), "UTF-8")

Das geht aber davon aus, dass alle Dateien als UTF-8 vorliegen. Wenn man das macht, sorgen alle nicht-ascii Zeichen, die in einer anderen Codierung als UTF-8 gespeichert werden, für einen Parser-Abbruch

2017-04-22 10:36 UTC, ByteHamster commented
Wie auch immer, besser als wenn die Dateien gar nicht geöffnet werden können. Hab es ins Javadoc eingefügt, dass wir UTF-8 fordern.

2017-04-23 19:01 UTC, HansMartinA approved these changes

2017-04-23 19:01 UTC, merged