[doc] Add and specify a few more criteria.
ByteHamster/PSE pull request #86
Opened 2016-12-10 11:11 UTC by NikoWil

Kriterien fuer die Fertigungssimulation eingefuegt.
Ein paar Formulierungen abgeaendert.

2016-12-10 11:34 UTC, Dav1dK requested changes

2016-12-10 11:34 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item Die von den \glspl{OPC UA Client} abgerufenen Werte und deren zeitlicher Verlauf werden graphisch dargestellt. Die Werte sind Zu- und Abflussmengen, Temperaturen,
Es gibt doch nur einen Client oder?

2016-12-10 11:34 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} setzt die \glspl{Sensordatum} in den \glspl{OPC UA Server}.
"setzt" klingt komisch, finde ich. Und es muss heißen "in DIE \glspl{OPC UA Server}."

2016-12-10 11:34 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
Ist das nicht eher so ein pro-user Feature, dass wir nicht unbedingt im Fplichtenheft haben wollen? Oder hab ich das falsch verstanden?

2016-12-10 11:45 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
Ich dachte, wenn es ein Feature ist sollte es drin stehen.
Aber auf jeden Fall als "Kann"

2016-12-10 11:47 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} setzt die \glspl{Sensordatum} in den \glspl{OPC UA Server}.
Ja. Setzen war nach meinem aktuellen Verstaendnis, dass wir wirklich direkt einen Setter dafuer aufrufen. Nochmal Hans Peter fragen, wie genau die Schnittstelle da ist.

Die wird eingefuegt.

2016-12-10 12:21 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} setzt die \glspl{Sensordatum} in den \glspl{OPC UA Server}.
Ich finde das ist zu technisch, zu viele Implementierungsdetails. Ich würde eher "überträgt" oder so verwenden.

2016-12-10 12:22 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
Ok. ich dachte dass ist ein undokumentiertes poweruser Feature, damit wir das nicht dokumentieren usw. müssen.

2016-12-10 14:29 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} setzt die \glspl{Sensordatum} in den \glspl{OPC UA Server}.
Setzen ist eigentlich technisch korrekter. Ist ein observer pattern, der Server holt sich seine Werte direkt aus den Attributen der `UAVariableNode`. Würde tatsächlich "setzen" schreiben, auch wenn es ein bisschen technisch ist. Dann ist es nämlich auf jeden Fall korrekt. Übertragen könnte man falsch verstehen

2016-12-10 14:31 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
Den Parser kann ich gern machen, das ist nicht schwer. Hab neulich einen Workshop zu sowas gemacht und einen Parser für eine kleine Interpretersprache geschrieben ;)

2016-12-10 14:31 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
Solange es eindeutig als "kann" drin ist, fände ich den einen Satz okay.

2016-12-10 14:35 UTC, ByteHamster requested changes

2016-12-10 14:35 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} setzt die \glspl{Sensordatum} in den \glspl{OPC UA Server}.
Die Fertigungssimulation **aktualisiert** die Sensordaten in den OPC UA Servern

2016-12-10 14:35 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} setzt die \glspl{Sensordatum} in den \glspl{OPC UA Server}.
Musst schauen, dass das \gls am Ende auch im richtigen Kasus ist

2016-12-10 16:16 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
Darum ist es ja als kann-Kriterium.

2016-12-11 08:37 UTC, ByteHamster requested changes

2016-12-11 08:37 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item In der \gls{Fertigungssimulation} und der \gls{Uberwachungskonsole} werden Probleme in der Programmausf\"uhrung geloggt.re
"re"?

2016-12-11 09:29 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +  \item In der \gls{Fertigungssimulation} und der \gls{Uberwachungskonsole} werden Probleme in der Programmausf\"uhrung geloggt.re
Ist raus.

2016-12-11 11:23 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    werden durch das Einf\"ugen eigener Dateien im entsprechenden Format erstellt.
OK das stimmt.

2016-12-11 11:24 UTC, Dav1dK approved these changes

2016-12-11 12:37 UTC, ByteHamster requested changes

2016-12-11 12:37 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item Die \gls{Fertigungssimulation} mit den \glspl{OPC UA Server} und die \gls{Uberwachungskonsole} mit den \glspl{OPC UA Client} laufen auf getrennten Rechnern.
`mit den \glspl{OPC UA Server}`? `mit den \glslink{OPC UA Server}{OPC UA Servern}`!

2016-12-11 12:38 UTC, ByteHamster approved these changes

2016-12-11 12:41 UTC, merged