[doc] Add more use cases
ByteHamster/PSE pull request #87
Opened 2016-12-10 14:11 UTC by Dav1dK

Make one use case out of alarm enabling, configuration and disabling.
Add more use cases to cover all requirements.

2016-12-10 14:13 UTC, Dav1dK commented
Sind jetzt schon 7 Anwendungsfälle. Eigentlich ein bisschen viel, aber wir sollen ja alle Anforderungen abdecken...

2016-12-10 14:23 UTC, ByteHamster commented on docs/Glossary.tex
> +\newglossaryentry{Prozessvariable}
Bitte alphabetisch

2016-12-10 14:26 UTC, ByteHamster requested changes

2016-12-10 14:26 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[Ausgangssituation] Die Prozessvariable ist geändert. Dies ist in der GUI der Fertigungssimulation sichtbar, etwa durch schnelleres befüllen oder leeren eines Tanks,
Befüllen und Leeren hier groß

2016-12-10 14:26 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +    \item Der Verbindungsaufbau schlägt fehlt und das Einstellungsfenster öffnet sich wieder.
Ein Dialog weist darauf hin, dass der Verbindungsaufbau fehlschlägt

2016-12-10 14:26 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +    \item Nachdem das \gls{Simulations-Szenario} fertig ist, wird die \gls{Fertigungssimulation} wieder auf den Anfangswert zurückgesetzt, und das
Hab ich auch schon gedacht, dass ein Reset dann sinnvoll ist :+1:

2016-12-10 15:18 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    \item Der Verbindungsaufbau schlägt fehlt und das Einstellungsfenster öffnet sich wieder.
Das würde ich im Einstellungsfenster anzeigen. D.h. ich würde oben (in roter Schrift) etwas schreiben wie: "Der Verbindungsaufbau ist gescheitert, bitte die Einstellungen anpassen".
Da würde ich keinen extra Dialog nehmen, sonst muss der Benutzer zu viel klicken.

2016-12-10 15:18 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    \item Nachdem das \gls{Simulations-Szenario} fertig ist, wird die \gls{Fertigungssimulation} wieder auf den Anfangswert zurückgesetzt, und das
Ja, vielleicht mit einer kurzen Einblendung, dass es jetzt einen Reset gab (damit der Benutzer nicht denkt, dass das ein Bug ist).

2016-12-10 16:51 UTC, NikoWil commented on docs/Glossary.tex
> +}
Ich wuerde die Erklaerung nur auf eine beziehen, das passt besser zum Namen. Die Beispiele aber lassen.

2016-12-10 16:51 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +    \item Nachdem das \gls{Simulations-Szenario} fertig ist, wird die \gls{Fertigungssimulation} wieder auf den Anfangswert zurückgesetzt, und das
Das spart uns auch den Teil mit "Wie stellen wir sicher, dass Endlosschleifen nicht in illegalen Zustaenden der Simulation enden?" :)

2016-12-10 16:51 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +    \item Der Verbindungsaufbau schlägt fehlt und das Einstellungsfenster öffnet sich wieder.
Sehe ich aehnlich. So wie man es ja auch von Websites etc. kennt, wenn zu wenige/ ungueltige Daten eingegeben wurden.
Warnung zeigen und nicht speichern lassen.

2016-12-10 23:04 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +\subsubsection{\glspl{Simulations-Szenario} verwenden}
Ich wuerde hier Singular nehmen.
Den Anwendungsfall durchfuehren fuehrt ja nur eines davon aus.

2016-12-10 23:09 UTC, NikoWil requested changes
Ich denke wir brauchen noch einen Anwendungsfall fuer die manuelle Steuerung der Simulation.
Das ist zz nicht vorhanden, wenn ich es richtig sehe.

2016-12-11 08:11 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\subsubsection{\glspl{Simulations-Szenario} verwenden}
Bitte auch keine glossaries in section Namen

2016-12-11 08:39 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +    \item Der Verbindungsaufbau schlägt fehlt und das Einstellungsfenster öffnet sich wieder.
Das heißt, der Verbindungsaufbau zum Server wird bei jeder Änderung sofort automatisch getestet? Was ist, wenn man während dem Test noch schnell auf "Speichern" drückt? Der Verbindungsaufbau dauert bei mir immer 1-2 Sekunden, trotz reduziertem Beispiel. Also Host und Ports würde ich erst beim "OK" klicken testen.

2016-12-11 10:31 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +    \item Der Verbindungsaufbau schlägt fehlt und das Einstellungsfenster öffnet sich wieder.
Ja klar, erst wenn man auf "Speichern" (so heißt es glaub ich in den GUI Entwürfen) drückt, wird die Verbindung aufgebaut und das Einstellungsfenster geschlossen. Und wenn es fehltschlägt, geht das Einstellungsfenster halt wieder auf.

2016-12-11 10:34 UTC, Dav1dK commented
Doch haben wir, das ist der Anwendungsfall "Änderung der Prozessvariablen".

2016-12-11 10:37 UTC, Dav1dK commented
@NikoWil: Ich würde die Verbindungseinstellungen nicht direkt beim Einstellen überprüfen (außer die Formatierung). Wie ByteHamster schon sage, dauert das zu lange. Ich würde die Verbindung erst neu aufbauen wenn der Benutzer auf "speichern" drückt. Wenn es fehlschlägt geht das Einstellungsfenster halt wieder auf.

2016-12-11 11:26 UTC, NikoWil approved these changes

2016-12-11 12:41 UTC, ByteHamster approved these changes

2016-12-11 12:48 UTC, merged