[doc] Modeling plant inside OPC-UA
ByteHamster/PSE pull request #90
Opened 2016-12-10 14:53 UTC by ByteHamster

2016-12-10 14:54 UTC, Dav1dK requested changes

2016-12-10 14:54 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} besteht aus vier Tanks. Drei der Tankss sind über Rohre mit dem vierten Tank verbunden.
Das steht (glaub ich) bei den GUI Anforderungen schon dabei.

2016-12-10 14:54 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
Sicher, dass das so ist? Dann wäre der Server doch kein eigener Prozess mehr, oder?

2016-12-10 14:58 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} besteht aus vier Tanks. Drei der Tankss sind über Rohre mit dem vierten Tank verbunden.
Außerdem ist da ein s zu viel ;)

Passt halt irgendwie von der Reihenfolge nicht, wenn man zuerst davon redet dass Farben drin sind, ohne zumindest mal erwähnt zu haben, dass Tanks modelliert werden sollen. Also zumindest einen groben Aufbau müsste man bei der Funktionalität schon beschreiben finde ich.

2016-12-10 15:16 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} besteht aus vier Tanks. Drei der Tankss sind über Rohre mit dem vierten Tank verbunden.
Deswegen hab ich bei manchen Anforderungen dann einen Verweis auf die entsprechenden GUI Anforderungen eingefügt. Also etwa: ...(siehe FAXXX)

2016-12-10 18:35 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
Gemeint ist damit, dass die nötigen Datenstrukturen angelegt werden, die die Anlage repräsentieren. Also Sensoren, Namen, Herstellernummern, xy

2016-12-10 18:36 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
Damit man im OPC auch die Anlage sieht

2016-12-10 18:36 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} besteht aus vier Tanks. Drei der Tankss sind über Rohre mit dem vierten Tank verbunden.
Okay mach ich weg

2016-12-10 18:59 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
Hast du eine bessere Idee, wie man es formulieren könnte?

2016-12-11 11:22 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
"Die per OPC UA übertragenen Werte der Produktionsanlage werden im OPC UA Server modelliert?"

2016-12-11 12:32 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
Hmm ne, die werden ja nicht per OPC UA an den Server übertragen. Die werden nur im Server so gesetzt dass es aussieht, als wäre der Server der, von dem die Daten ursprünglich kommen.

2016-12-11 13:50 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +  \item[FA10] Die \gls{Produktionsanlage} wird innerhalb der \gls{OPC UA Server} modelliert.
So meinte ich das auch nicht. Es fällt mir aber schwer, eine bessere Formulierung zu finden. Dann lassen wir es so.

2016-12-11 13:50 UTC, Dav1dK approved these changes

2016-12-11 15:10 UTC, merged