Activitydiagram
ByteHamster/PSE pull request #92
Opened 2016-12-10 16:43 UTC by Dav1dK

2016-12-10 18:30 UTC, ByteHamster requested changes
in main-simulation.png schreibt der Text über einen Strich raus. Vielleicht lieber mit einzelnem Textfeld lösen

2016-12-10 18:30 UTC, ByteHamster commented
Ach ja, mach bitte noch einen rebase, dann würde ich es nämlich mit merge commit machen

2016-12-10 18:34 UTC, ByteHamster requested changes
Grafiken und Inhalt sind super!

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\subsubsection{Starten der \gls{Uberwachungskonsole}}
glossary in sections sollte man nicht machen. Bekomme da Warnungen im Code angezeigt, weil das PDF dann möglicherweise Probleme bekommt (Link in Kapitelname)

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> + \item Die Überwachungskonsole versucht, die Verbindung zu den \glspl{OPC UA Server} mit den zuletzt gespeicherten Verbindungsinformationen aufzunehmen.
Hier glossary verlinken

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> + \item Wenn der Verbindungsaufbau geklappt hat, zeigt die \gls{Uberwachungskonsole} die Übertragenen Werte der \gls{Fertigungssimulation}, sowie die
Übertragenen klein

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\end{center}
Grafiken bitte so einbinden, dass sie im Abbildungsverzeichnis gefunden werden. Einfach an den schon vorhandenen Grafiken orientieren

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\subsubsection{Hauptschleife und Alarme der \gls{Uberwachungskonsole}}
Glossary im Titel

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\end{center}
Abbildungsverzeichnis

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> + \item Wenn durch eine Zustandsänderung eine Alarmschwelle überschritten wurde, wird der Alarm an alle OPC UA Clients gesendet,
OPC UA Clients glossary

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +\subsubsection{Hauptschleife der \gls{Fertigungssimulation}}
Link in Titel

2016-12-10 18:34 UTC, ByteHamster commented on docs/Pflichtenheft.tex
> +  \includegraphics[scale=0.62]{media/Activities/main-simulation.png}
Abbildungsverzeichnis

2016-12-11 10:42 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +\subsubsection{Starten der \gls{Uberwachungskonsole}}
Stimmt, das Problem hatte ich auch schonmal.

2016-12-11 12:29 UTC, ByteHamster approved these changes

2016-12-11 12:29 UTC, merged