[doc] Removed 'kann' from required criteria
ByteHamster/PSE pull request #93
Opened 2016-12-10 18:46 UTC by ByteHamster

Also removed menu descriptions

2016-12-11 09:52 UTC, NikoWil submitted a review, later dismissed

2016-12-11 09:52 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +  \item[FA610] In den Einstellungen werden die IP-Adresse des \glslink{OPC UA Client}{OPC UA Clients} und der \gls{OPC UA Server}, sowie deren Ports angezeigt.
Fuer die IP-Adresse gibt es einen Glossareintrag. Wurde vorher wohl vergessen. Kannst du den noch schnell ergaenzen? :)

2016-12-11 09:52 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +  \item[FA570] In den Einstellungen ist der Port für den \gls{OPC UA Client} bzw. die Ports und die IP-Adresse für die \glspl{OPC UA Server} konfigurierbar.
IP-Adresse.
Sind es jetzt nicht mehrere Clients?

2016-12-12 22:20 UTC, HansMartinA requested changes

2016-12-12 22:20 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +  \item[FA610] In den Einstellungen werden die \glslink{TCP/IP}{IP-Adresse} der \glslink{OPC UA Client}{OPC UA Clients} und der \gls{OPC UA Server}, sowie deren Ports angezeigt.
Das Komma nach \gls{OPC UA Server} ist falsch. Außerdem: Wenn du hier die Einteilung der Reiter entfernst, musst du es auch noch in den optionalen Funktionalitäten machen oder ich mache es später.

2016-12-12 22:20 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +  \item[FA590] Der Menüeintrag "`Über'" öffnet ein neues Fenster, in dem der Programmname, die Version, das Programmsymbol und die Lizenz angezeigt werden.
Ich hätte hier noch explizit die Lizenzen verwendeter Bibliotheken / Projekte erwähnt, damit klar ist, dass diese auch einen Platz bekommen bzw. wo dieser Platz ist.

2016-12-12 22:33 UTC, HansMartinA approved these changes

2016-12-12 22:34 UTC, merged