[doc] Global test cases
ByteHamster/PSE pull request #97
Opened 2016-12-10 19:59 UTC by HansMartinA

Ein paar Anmerkungen: Ich habe alle Nummern der FAs angepasst, da ich mich in den Testfällen darauf beziehe und dafür eindeutige Nummern brauche, damit dort nichts durcheinander gerät. Außerdem habe ich im Übrigen solche globalen Testfälle noch nie geschrieben.

2016-12-10 21:37 UTC, ByteHamster requested changes
Mit dem hier sollten wir auf jeden Fall warten, bis die anderen drin sind. Sonst bekommen die alle Konflikte...

2016-12-10 21:37 UTC, ByteHamster commented on .gitignore
> +.settings/
Warum das?

2016-12-11 08:49 UTC, ByteHamster commented
Ich finde auch, dass wir zuerst nochmal über die Reihenfolge der FA nachdenken sollten, bevor wir das final benennen

2016-12-11 11:20 UTC, Dav1dK reviewed
Sieht gut aus, ich habe jetzt aber nicht alle FA Nummer überprüft, das wird schon passen ;)

2016-12-11 11:20 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +   IP-Adresse und falschen Ports für die \glspl{OPC UA Server} der \gls{Fertigungssimulation} gestartet, sodass eine Fehlermeldung für den Benutzer erscheint (FA450).
IP-Adresse ODER falschen Ports?

2016-12-11 11:22 UTC, HansMartinA commented on docs/Pflichtenheft.tex
> +   IP-Adresse und falschen Ports für die \glspl{OPC UA Server} der \gls{Fertigungssimulation} gestartet, sodass eine Fehlermeldung für den Benutzer erscheint (FA450).
Eigentlich meinte ich UND, sollte bei dem Testfall aber keine Rolle spielen, da es darum geht, dass keine Verbindung hergestellt werden kann.

2016-12-11 11:23 UTC, HansMartinA commented on .gitignore
> +.settings/
Das ist irgendetwas schief gegangen. Bei mir hat git gestern Abend lokal alles zerstört.

2016-12-11 11:26 UTC, Dav1dK commented on docs/Pflichtenheft.tex
> +   IP-Adresse und falschen Ports für die \glspl{OPC UA Server} der \gls{Fertigungssimulation} gestartet, sodass eine Fehlermeldung für den Benutzer erscheint (FA450).
OK, ist eigentlich auch genauer mit UND. Ich dachte nur, dass es vielleicht mehr abdeckt wenn wir ODER schreiben, aber ich denke dann ist es zu ungenau spezifiziert. Dann lass es mit UND.

2016-12-13 18:26 UTC, NikoWil approved these changes

2016-12-13 18:26 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +  \item[GT100] \textbf{Öffnen der \gls{Fertigungssimulation}}: Eine .jar-Datei startet bei Ausführung die \gls{Fertigungssimulation} und die \glspl{OPC UA Server} (FA70).
Eine jar Datei je Programm, die sind ja potentiell auf verschiedenen Rechnern.

2016-12-13 18:26 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +   Werte aus diesem Zeitraum werden im Verlauf werden währenddessen noch danach angezeigt.
[...] werden _weder_ waehrenddessen [...]

2016-12-13 18:26 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +   Dies wiederum darf in der \gls{Uberwachungskonsole} nicht angezeigt werden.
Den zweiten Satz wuerde ich anders machen.
"In der \gls{Uberwachungskonsole} wird kein Alarm angezeigt."
Wir gehen ja davon aus, dass es funktioniert und dann ist der Satz einfacher :)

2016-12-13 18:26 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +   Alle verfügbaren \glspl{Simulations-Szenario} werden nacheinander korrekt ausgeführt (FA150, 160, 310), ohne dass es eine Bedingung durch den Nutzer benötigt.
[...] ausgefuehrt (FA150, 160, 310). Der Nutzer muss nicht eingreifen.

2016-12-13 18:26 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +   Temperaturen aller Tanks (FA10, FA20, FA60) sowie die Drehzahl des Mischers (FA30) in der \gls{Fertigungssimulation} neu eingestellt und wieder auf ihren Standardwert zurückgesetzt.
Die Temperatur des unteren Tanks ist nicht einstellbar.
Man sieht aber die Auswirkungen, wenn die Temperaturen der oberen Tanks geaendert werden.

2016-12-13 18:26 UTC, NikoWil commented on docs/Pflichtenheft.tex
> +   erden die \glspl{Sensordatum} wieder abgerufen (FA830).
werden statt erden.

2016-12-13 18:26 UTC, ByteHamster approved these changes

2016-12-13 18:32 UTC, merged